language: cpp

compiler:
  - clang

before_script:
  - sudo apt-get update -qq
  # google-gflags
  - wget https://github.com/gflags/gflags/releases/download/v2.1.0/libgflags0_2.1.0-1_amd64.deb
  - wget https://github.com/gflags/gflags/releases/download/v2.1.0/libgflags-dev_2.1.0-1_amd64.deb
  - sudo dpkg -i libgflags0_2.1.0-1_amd64.deb
  - sudo dpkg -i libgflags-dev_2.1.0-1_amd64.deb
  # google-glog
  - pushd $HOME
  - svn checkout http://google-glog.googlecode.com/svn/trunk/ google-glog
  - cd google-glog
  - mkdir _build
  - cd _build
  - ../configure --prefix=/usr
  - make -j4
  - sudo make install
  - popd
  # build puyoai
  - cd $HOME
  - mkdir -p out/Debug
  - cd out/Debug
  - cmake -DCMAKE_BUILD_TYPE=DEBUG ../../src

script:
  - make
  - make test
