name = "tsubushi"

[me]
field = [
    "R.....",
    "B.....",
    "R.....",
    "BR....",
    "BR....",
    "BYG...",
    "RBYG..",
    "RBYG..",
    "RBYG..",
]
next = "RBYGGB"

[enemy]
field = [
    "BOOOOO",
    "ROOOOO",
    "BGOOOO",
    "GGOOOO",
    "BOOOOO",
    "BGOOOO",
    "BYGYGO",
    "RBYGYG",
    "RBYGYG",
    "RBYGYG",
]
next = "YYYYYY"

[answer]
answers = [
    [2, 0]
]
