[[book]]
field = []
AAAA = [3, 2]
AAAB = [3, 3]
AABB = [3, 3]
AABC = [1, 2]
ABAA = [3, 0]
ABAB = [2, 2]
ABAC = [1, 1]
ABCC = [2, 2]

[[book]]
field = [
    "..A...",
    "..A..."
]
AAAA = [5, 2]
AAAB = [3, 0]
AAAC = [3, 0]
AABB = [3, 0]
AABC = [3, 0]

[[book]]
field = [
    "A.....",
    "A....."
]
BCAA = [2, 2]
BCAB = [3, 1]  # TODO: [2, 2]?
BCAC = [4, 3]
BCBB = [2, 0]
BCBC = [2, 2]

[[book]]
field = [
    ".AA..."
]
ABAB = [1, 0]
ABAC = [1, 0]
ABBB = [1, 0]
ABBC = [1, 0]
ABCC = [4, 2]
BBAA = [1, 2]  # TODO: other?
BBBB = [3, 3]
BBBC = [3, 3]
BBCC = [3, 3]
BCAB = [2, 0]

[[book]]
field = [
    "AA...."
]
ABAB = [3, 0]
ABCC = [3, 0]

[[book]]
field = [
    "AB...."
]
ACAA = [1, 1]
ACAB = [1, 1]
ACAC = [1, 1]
ACBB = [1, 0]
ACBC = [1, 1]
ACCC = [1, 1]

[[book]]
field = [
    "..B...",
    "..A..."
]
AAAC = [2, 3]
AACC = [2, 3]
ABAB = [2, 0]
ACAB = [1, 0]
ACAC = [2, 0]
ACCC = [2, 3]

[[book]]
field = [
    ".B....",
    ".A...."
]
ABAA = [3, 0]
ABAB = [3, 0]
ABAC = [1, 0]
ABBB = [3, 0]
ABCC = [3, 0]
ABBC = [3, 0]
CCAB = [5, 1]
CCAC = [1, 2]

# ----------------------------------------------------------------------

[[book]]
field = [
    "AABC.."
]
CCBD = [5, 1]

[[book]]
field = [
    "AC....",
    "AB...."
]
ABBB = [2, 1]
ABAD = [2, 3]
ABBD = [2, 3]
ACAB = [1, 1]
ACAC = [2, 3]
ACBC = [2, 3]
ACDD = [5, 3]  # TODO: [1, 1] is better?
BBCB = [1, 2]
BCBC = [3, 0]
BCAC = [3, 0]
BDAB = [3, 1]

[[book]]
field = [
    ".BB...",
    ".AA..."
]
AAAC = [5, 1]  # TODO: [2, 3] ?
AACC = [5, 1]  # TODO: [2, 3] ?
ACAB = [4, 2]
ACAC = [4, 2]
ACAD = [4, 2]
BCBC = [1, 0]
BCBD = [4, 1]
BCCC = [4, 0]
BCCD = [4, 1]
CCAC = [1, 2]
CCBC = [5, 1]
CCBD = [1, 2]
CCCC = [1, 2]

[[book]]
field = [
    "B.....",
    "AAA...",
]
ABBC = [2, 2]
ACAB = [4, 2]
ACAD = [4, 0]  # TODO: [3, 2] ?
BCBD = [2, 0]

[[book]]
field = [
    "..B...",
    "AAA..."
]
ABAB = [2, 2]
ABBC = [2, 2]
ACBB = [4, 2]
ACBD = [4, 2]
ACDD = [4, 2]
BCAD = [1, 0]
BCAC = [4, 1]
CCAB = [5, 1]  # TODO: [1, 2] ?

[[book]]
field = [
    "B.C...",
    "A.A..."
]
ACCD = [2, 0]

[[book]]
field = [
    "A.....",
    "A.BC.."
]
ABAD = [2, 0]

[[book]]
field = [
    "C.....",
    "A.....",
    "AB...."
]
BBAD = [3, 2]

# ----------------------------------------------------------------------

[[book]]
field = [
    "BBB...",
    "AAA..."
]
ACBC = [3, 3]
BCAB = [4, 0]

[[book]]
field = [
    ".A....",
    ".BB...",
    "AAA..."
]
BCAB = [1, 0]
BCBC = [4, 1]
BCCD = [4, 1]

[[book]]
field = [
    ".BB...",
    ".AABB."
]
BCBD = [6, 0]

[[book]]
field = [
    "BBC...",
    "AAA..."
]
BCBB = [3, 1]

[[book]]
field = [
    "BCC...",
    "AAA...",
]
ADBB = [4, 2]
CDAD = [2, 0]

[[book]]
field = [
    "ACC...",
    "ABB...",
]
ADBC = [3, 0]
CDCD = [4, 1]

[[book]]
field = [
    ".CC...",
    ".AA.BB"
]
ABAB = [4, 2]

[[book]]
field = [
    "C.....",
    "B.B...",
    "AAA..."
]
ACCC = [4, 2]
ADAC = [4, 2]

[[book]]
field = [
    ".AAC..",
    ".CCB..",
]
CDCD = [3, 1]

[[book]]
field = [
    ".BB...",
    ".AABC."
]
CDCD = [6, 0]
DDAC = [1, 2]

[[book]]
field = [
    ".B....",
    ".AABCC",
]
BDCD = [3, 0]  # TODO: other?

[[book]]
field = [
    "..B...",
    "AAABC."
]
ACDD = [6, 2]

[[book]]
field = [
    "CA....",
    "AC....",
    "AB...."
]
BDCD = [3, 1]

# ----------------------------------------------------------------------

[[book]]
field = [
    ".AA...",
    "ACC...",
    "ABB..."
]
ADAD = [6, 2]
ADBD = [6, 2]

[[book]]
field = [
    "BA....",
    "ACC...",
    "ABB..."
]
BBAD = [5, 1]
BBAC = [1, 2]

[[book]]
field = [
    "CA....",
    "ACC...",
    "ABB..."
]
CCAB = [1, 2]
