BOOK = 27
BOOK_KIND = 20
TOTAL_FRAMES = -0.1
FIRE_POINT_TABOO = -120
NUM_CHIGIRI = -50
NUM_GARBAGE_PUYOS = -5
NUM_SIDE_GARBAGE_PUYOS = -20
CONNECTION_2 = 5
CONNECTION_3 = 15
CONNECTION_AFTER_DROP_2 = 1
CONNECTION_AFTER_DROP_3 = 3
CONNECTION_HORIZONTAL_2 = 10
CONNECTION_HORIZONTAL_3 = 30
CONNECTION_HORIZONTAL_CROSSED_2 = -10
CONNECTION_HORIZONTAL_CROSSED_3 = -20
THIRD_COLUMN_HEIGHT = [
        0,     0,     0,   -30,   -40,   -50,   -60,   -70,   -80,  -200,
    -2000, -7000, -9000, -9000, -9000, -9000]
STRATEGY_INITIAL_ZENKESHI = 50000
STRATEGY_ZENKESHI = 500
STRATEGY_TAIOU = 50000
STRATEGY_LARGE_ENOUGH = 100000
STRATEGY_TSUBUSHI = 32000
STRATEGY_SAKIUCHI = -1500
STRATEGY_LAND_LEVELING = 0
STRATEGY_SCORE = 0.1
STRATEGY_SAISOKU = 8500
STRATEGY_ZENKESHI_CONSUME = 72000
STRATEGY_IBARA = 10000
MAX_CHAINS = [
     0,  1000,  2000,  3000,  4000,  5000,  6000,  7000,  8000,  9000,
 10000, 11000, 12000, 13000, 14000, 15000, 16000, 17000, 18000, 19000,
]
NECESSARY_PUYOS_EARLY_LINEAR = -40
NECESSARY_PUYOS_EARLY_SQUARE = -5.3
NECESSARY_PUYOS_MIDDLE_LINEAR = -80
NECESSARY_PUYOS_MIDDLE_SQUARE = -6
NECESSARY_PUYOS_LATE_LINEAR = -130
NECESSARY_PUYOS_LATE_SQUARE = -7
#HAND_WIDTH_2 = [   0,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9]
#HAND_WIDTH_3 = [   0,   0, 200, 300, 300, 300, 300, 300, 300, 300, 300]
HAND_WIDTH_4 = [   0,   0, 200, 400, 500, 500, 500, 500, 500, 500, 500]
#HAND_WIDTH_4 = [   0,   0, 400, 400, 500, 500, 500, 500, 500, 500, 500]
VALLEY_DEPTH = [0, 0, -15, -20, -2000, -3000, -4000, -4000, -4000, -4000, -4000, -4000, -4000, -4000, -4000]
RIDGE_HEIGHT = [0, 0, -15, -20, -2000, -3000, -4000, -4000, -4000, -4000, -4000, -4000, -4000, -4000, -4000]
IGNITION_HEIGHT = [0, 0, 0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110]
IGNITION_HEIGHT_ON_ENEMY_ZENKESHI = [0, 500, 2000, 3000, 4000, 5000, 10000, 12000, 13000, 14000, 15000, 16000, 17000, 18000]
FIELD_USHAPE_LINEAR = -0.1
FIELD_USHAPE_SQUARE = -1.8
FIELD_USHAPE_EXP = -0.1
FIELD_USHAPE_LINEAR_ON_ZENKESHI = -1000
FIELD_USHAPE_SQUARE_ON_ZENKESHI = 0
FIELD_USHAPE_EXP_ON_ZENKESHI = 0
NUM_UNREACHABLE_SPACE = -2000
MIDEVAL_ERASE = -1200
MIDEVAL_RESULT = 0.0001
