PATTERN_BOOK = 10
RENSA_KIND = 2
TOTAL_FRAMES = -0.1
FIRE_POINT_TABOO = -120
COMPLEMENTATION_BIAS = -50
COMPLEMENTATION_BIAS_EDGE = -700
COMPLEMENTATION_BIAS_MUCH = -50
SCORE = 0
VIRTUAL_SCORE = 0
NUM_CHIGIRI = -50
NUM_GARBAGE_PUYOS = -5
NUM_SIDE_GARBAGE_PUYOS = -20
CONNECTION_2 = 5
CONNECTION_3 = 15
CONNECTION_AFTER_DROP_2 = 1
CONNECTION_AFTER_DROP_3 = 3
CONNECTION_HORIZONTAL_2 = 8
CONNECTION_HORIZONTAL_3 = 15
CONNECTION_HORIZONTAL_CROSSED_2 = -10
CONNECTION_HORIZONTAL_CROSSED_3 = -20
THIRD_COLUMN_HEIGHT = [
        0,     0,     0,   -30,   -40,   -50,   -60,   -70,   -80,  -200,
    -2000, -7000, -9000, -9000, -9000, -9000]
STRATEGY_KILL = 150000
STRATEGY_KILL_FRAME = -100
STRATEGY_LARGE_ENOUGH = 100000
STRATEGY_INITIAL_ZENKESHI = 50000
STRATEGY_ZENKESHI = 500
STRATEGY_TAIOU = 50000
STRATEGY_TSUBUSHI = 32000
STRATEGY_SAKIUCHI = -1500
STRATEGY_LAND_LEVELING = 0
STRATEGY_SCORE = 0.1
STRATEGY_SAISOKU = 8500
STRATEGY_ZENKESHI_CONSUME = 72000
STRATEGY_IBARA = 0
MAX_CHAINS = [
     0,  1000,  2000,  3000,  4000,  5000,  6000,  7000,  8000,  9000,
 10000, 11000, 12000, 13000, 14000, 15000, 16000, 17000, 18000, 19000,
]
NECESSARY_PUYOS_LINEAR = -80
NECESSARY_PUYOS_SQUARE = -6
IGNITION_HEIGHT = [0, 0, 0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110]
IGNITION_HEIGHT_ON_ENEMY_ZENKESHI = [0, 500, 2000, 3000, 4000, 5000, 10000, 12000, 13000, 14000, 15000, 16000, 17000, 18000]
VALLEY_DEPTH = [0, 0, -15, -20, -2000, -3000, -4000, -4000, -4000, -4000, -4000, -4000, -4000, -4000, -4000]
RIDGE_HEIGHT = [0, 0, -15, -20, -2000, -3000, -4000, -4000, -4000, -4000, -4000, -4000, -4000, -4000, -4000]
RENSA_VALLEY_DEPTH = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
RENSA_RIDGE_HEIGHT = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
FIELD_USHAPE_LINEAR = -0.1
FIELD_USHAPE_SQUARE = -1.6
FIELD_USHAPE_EXP = -0.1
RENSA_FIELD_USHAPE_LINEAR = 0
RENSA_FIELD_USHAPE_SQUARE = -5
RENSA_FIELD_USHAPE_EXP = 0
NUM_UNREACHABLE_SPACE = -2000
MIDEVAL_ERASE = -1800
MIDEVAL_RESULT = 0.0001
HOLDING_FAST_CHAIN_MEDIUM = 80
HOLDING_FAST_CHAIN_LARGE  = 120

[mode.early]
PATTERN_BOOK = 140
NUM_CHIGIRI = -100
NECESSARY_PUYOS_LINEAR = -40
NECESSARY_PUYOS_SQUARE = -5.3
THIRD_COLUMN_HEIGHT = [
        0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
        0,     0,     0,     0,     0,     0]

[mode.early_middle]
PATTERN_BOOK = 80
NECESSARY_PUYOS_LINEAR = -60
NECESSARY_PUYOS_SQUARE = -5.7

[mode.middle]
NECESSARY_PUYOS_LINEAR = -80
NECESSARY_PUYOS_SQUARE = -6
HOLDING_SIDE_CHAIN_SMALL  = 1300
HOLDING_SIDE_CHAIN_MEDIUM = 1500
HOLDING_SIDE_CHAIN_LARGE  = 1800
STRATEGY_FIRE_SIDE_CHAIN_LARGE = 4000
STRATEGY_FIRE_SIDE_CHAIN_MEDIUM = 3500
STRATEGY_FIRE_SIDE_CHAIN_SMALL = 2500
STRATEGY_IBARA = 10000

[mode.late]
VIRTUAL_SCORE = 0.3
NECESSARY_PUYOS_LINEAR = -140
NECESSARY_PUYOS_SQUARE = -8
HOLDING_SIDE_CHAIN_SMALL  = 2100
HOLDING_SIDE_CHAIN_MEDIUM = 2400
HOLDING_SIDE_CHAIN_LARGE  = 2700
STRATEGY_FIRE_SIDE_CHAIN_LARGE = 6000
STRATEGY_FIRE_SIDE_CHAIN_MEDIUM = 5000
STRATEGY_FIRE_SIDE_CHAIN_SMALL = 4000
STRATEGY_IBARA = 10000

[mode.enemy_has_zenkeshi]
FIELD_USHAPE_LINEAR = -1000
FIELD_USHAPE_SQUARE = 0
FIELD_USHAPE_EXP = 0
RENSA_FIELD_USHAPE_LINEAR = 0
RENSA_FIELD_USHAPE_SQUARE = 0
RENSA_FIELD_USHAPE_EXP = 0
