[[book]]
field = []
AAAA = [3, 2]
AAAB = [2, 3]
AABB = [3, 3]
AABC = [3, 3]
ABAA = [3, 0]
ABAB = [2, 2]
ABAC = [3, 0]
ABCC = [3, 1]

[[book]]
field = [
    "..A...",
    "..A..."
]
AAAA = [5, 2]
AAAB = [3, 0]
AAAC = [3, 0]
AABB = [3, 0]
AABC = [3, 0]

[[book]]
field = [
    ".AA..."
]
BBBB = [3, 3]
BBCC = [3, 3]

[[book]]
field = [
    "AA...."
]
ABAB = [3, 0]

[[book]]
field = [
    "..B...",
    "..A..."
]
ABAB = [2, 0]
ACAC = [2, 0]
ACCC = [2, 3]

[[book]]
field = [
    ".B....",
    ".A...."
]
ABAB = [3, 0]
ABCC = [3, 0]
ABAC = [3, 0]
