[[book]]
field = []
AAAA = [3, 2]
AAAB = [2, 3]
AABB = [3, 3]
AABC = [1, 2]
ABAA = [3, 0]
ABAB = [2, 2]
ABAC = [3, 0]
ABCC = [2, 2]

[[book]]
field = [
    "..A...",
    "..A..."
]
AAAA = [5, 2]
AAAB = [3, 0]
AAAC = [3, 0]
AABB = [3, 0]
AABC = [3, 0]

[[book]]
field = [
    "A.....",
    "A....."
]
BCAC = [4, 3]

[[book]]
field = [
    ".AA..."
]
BBBB = [3, 3]
BBCC = [3, 3]
BCAB = [2, 0]

[[book]]
field = [
    "AA...."
]
ABAB = [3, 0]
ABCC = [3, 0]

[[book]]
field = [
    "..B...",
    "..A..."
]
AACC = [3, 3]
ABAB = [2, 0]
ACAB = [1, 0]
ACAC = [2, 0]
ACCC = [2, 3]

[[book]]
field = [
    ".B....",
    ".A...."
]
ABAB = [3, 0]
ABCC = [3, 0]
ABAC = [3, 0]
CCAB = [1, 2]
CCAC = [1, 2]

[[book]]
field = [
    "AABC.."
]
CCBD = [5, 1]

[[book]]
field = [
    "AC....",
    "AB...."
]
ACDD = [5, 3]  # TODO: [1, 1] is better?
BBCB = [1, 2]

[[book]]
field = [
    ".BB...",
    ".AA..."
]
ACAB = [4, 2]
ACAC = [4, 2]
ACAD = [4, 2]

[[book]]
field = [
    "..B...",
    "AAA..."
]
BCAD = [1, 0]

[[book]]
field = [
    "B.C...",
    "A.A..."
]
ACCD = [2, 0]

[[book]]
field = [
    "BBC...",
    "AAA..."
]
BCBB = [3, 1]

[[book]]
field = [
    "BBB...",
    "AAA..."
]
ACBC = [3, 3]

[[book]]
field = [
    ".AAC..",
    ".CCB..",
]
CDCD = [3, 1]

[[book]]
field = [
    ".AA...",
    "ACC...",
    "ABB..."
]
ADBD = [6, 2]

[[book]]
field = [
    "BA....",
    "ACC...",
    "ABB..."
]
BBAD = [5, 1]
