
[[book]]
field = [
    "b.....",
    "BE....",
    "EE....",
    "BAD...",
    "BBA...",
    "AAC..."
]
name = "GTR2-HEAD"
score = 10.0

[[book]]
field = [
    "b.....",
    "B.....",
    "E.....",
    "EE....",
    "BAD...",
    "BBA...",
    "AAC..."
]
name = "GTR2-HEAD"
score = 9.0

[[book]]
field = [
    ".....c",
    "....cC",
    "..DXXX",
    "...DDD",
    "..CCCX"
]
name = "GTR2-TAIL"
score = 9.5

[[book]]
field = [
    "...xXx",
    "..DXCX",
    "...DDD",
    "..CCCX"
]
name = "GTR2-TAIL"
score = 9.5

[[book]]
field = [
    "..D.X.",
    "...DDD",
    "..CXXX"
]
name = "GTR2-TAIL"
score = 9.5

[[book]]
name = "GTR2-TAIL"
score = 8.50000
field = [
    ".....Y",
    "....XY",
    "..D.XY",
    "...DDX",
    "..CDYX"
]

[[book]]
name = "GTR2-TAIL"
score = 8.50000
field = [
    ".....Y",
    "....XY",
    "..D.XY",
    "...DYX",
    "..CDDX"
]

[[book]]
name = "GTR-TAIL"
score = 8.5
field = [
    "..DE..",
    "...DDE",
    "..CDEE"
]



[[book]]
field = [
    "b.....",
    "Bb....",
    "E.....",
    "D.....",
    "DEE...",
    "DEAC..",
    "BBBA..",
    "AAAC.."
]
name = "NEWGTR-HEAD"
score = 8.8

[[book]]
name = "NEWGTR-HEAD"
score = 8.0
field = [
    ".D....",
    "BD....",
    "DEE...",
    "DEAC..",
    "BBBA..",
    "AAAC.."
]

[[book]]
name = "NEWGTR-HEAD"
score = 9.7
field = [
    "B.....",
    "D.....",
    "D.....",
    "E.....",
    "DEE...",
    "DFAC..",
    "BBBA..",
    "AAAC.."
]

[[book]]
name = "NEWGTR-HEAD"
score = 9.6
field = [
    "B.....",
    "D.....",
    "D.....",
    "E.....",
    "EE....",
    "DDAC..",
    "BBBA..",
    "AAAC.."
]

[[book]]
name = "NEWGTR-TAIL"
score = 10.0
field = [
    ".....x",
    "...cxX",
    "...CxX",
    "....CC",
    "...CXX"
]

[[book]]
name = "NEWGTR-TAIL"
score = 10.0
field = [
    "...c.X",
    "...CXX",
    "....CC",
    "...CYX"
]

[[book]]
name = "NEWGTR-TAIL"
score = 9.8
field = [
    "...c.X",
    "...CXX",
    "....CC",
    "...CXC"
]

[[book]]
name = "NEWGTR-TAIL"
score = 9.0
field = [
    "...cxx",
    "...CXX",
    "....CC",
    "...CXX"
]

[[book]]
name = "NEWGTR-TAIL"
score = 9.0
field = [
    ".....Y",
    "...CXY",
    "...CXY",
    "....CX",
    "...CXY"
]

[[book]]
name = "NEWGTR-TAIL"
score = 9.0
field = [
    ".....Y",
    "...CXY",
    "...CXX",
    "....CY",
    "...CXY"
]

[[book]]
name = "NEWGTR-TAIL"
score = 2.0
field = [
    ".....Y",
    "...CXY",
    "...CXY",
    "....YX",
    "...CCX"
]

[[book]]
name = "NEWGTR-TAIL"
score = 2.0
field = [
    ".....Y",
    "...CXY",
    "...CYX",
    "....YX",
    "...CCX"
]

[[book]]
name = "NEWGTR-TAIL"
score = 9.0
field = [
    ".....y",
    "....yY",
    "....YX",
    "...CXX",
    "....CC",
    "...CXY"
]

[[book]]
name = "NEWGTR-TAIL"
score = 9.0
field = [
    "....X.",
    "...CX.",
    "....CX",
    "...CCX"
]

[[book]]
name = "NEWGTR-TAIL"
score = 9.0
field = [
    ".....Y",
    ".....Y",
    "....XY",
    "...CYX",
    "....CX",
    "...CCX"
]

[[book]]
name = "NEWGTR-TAIL"
score = 8.8
field = [
    "....YY",
    "....XY",
    "...CYX",
    "....CX",
    "...CCX"
]

# ----------------------------------------------------------------------

[[book]]
name = "NEWGTR2-HEAD"
score = 10.0
field = [
    ".b....",
    "DBb...",
    "DDAE..",
    "BBBA..",
    "AAAC.."
]

[[book]]
field = [
    "b.....",
    "Bb....",
    "D.....",
    "DDAE..",
    "BBBA..",
    "AAAC.."
]
name = "NEWGTR2-HEAD"
score = 10.0

[[book]]
field = [
    "b.....",
    "BD....",
    "DDAE..",
    "BBBA..",
    "AAAC.."
]
name = "NEWGTR2-HEAD"
score = 10.0

[[book]]
field = [
    "B.....",
    "DD....",
    "DFAE..",
    "BBBA..",
    "AAAC.."
]
name = "NEWGTR2-HEAD"
score = 10.0

[[book]]
field = [
    "b.....",
    "B.....",
    "F.....",
    "F.....",
    "F.....",
    "DD....",
    "DFAE..",
    "BBBA..",
    "AAAC.."
]
name = "NEWGTR2-HEAD"
score = 10.0

[[book]]
field = [
    "b.....",
    "B.....",
    "F.....",
    "F.....",
    "D.....",
    "DFf...",
    "DFAE..",
    "BBBA..",
    "AAAC.."
]
name = "NEWGTR2-HEAD"
score = 10.0

[[book]]
field = [
    "B.....",
    "D.....",
    "D.....",
    "G.....",
    "DGG...",
    "DFAE..",
    "BBBA..",
    "AAAC.."
]
name = "NEWGTR2-HEAD"
score = 9.7

[[book]]
name = "NEWGTR2-HEAD"
score = 9.7
field = [
    "B.....",
    "D.....",
    "D.....",
    "GG....",
    "DG....",
    "DFAE..",
    "BBBA..",
    "AAAC.."
]

[[book]]
field = [
    "...E..",
    "....EE",
    "...CEX"
]
name = "NEWGTR2-TAIL"
score = 9.5

[[book]]
field = [
    "....cc",
    "...ECC",
    "....EE",
    "...CEC"
]
name = "NEWGTR2-TAIL"
score = 9.8

[[book]]
field = [
    "...e..",
    "...ECE",
    "....EE",
    "...CCC"
]
name = "NEWGTR2-TAIL"
score = 7.8

[[book]]
name = "NEWGTR2-TAIL"
score = 8.0
field = [
    ".....X",
    "...XCX",
    "...EXE",
    "....EE",
    "...CCC"
]

[[book]]
field = [
    "...ecc",
    "...ECC",
    "....EE",
    "...CCE"
]
name = "NEWGTR2-TAIL"
score = 9.8

[[book]]
field = [
    "....xc",
    "...*XC",
    "...ECX",
    "....EE",
    "...CCE"
]
name = "NEWGTR2-TAIL"
score = 9.8

[[book]]
field = [
    "....xX",
    "...EXE",
    "....EE",
    "...CXX"
]
name = "NEWGTR2-TAIL"
score = 8.2

[[book]]
name = "NEWGTR2-TAIL"
score = 8.0
field = [
    ".....X",
    "...EXX",
    "...ECC",
    "....EE",
    "...CCX"
]

[[book]]
name = "NEWGTR2-TAIL"
score = 5.0
field = [
    "...EE.",
    "...AAA",
    "...CEE"
]

# ----------------------------------------------------------------------

[[book]]
name = "LTR-KEY"
score = 1.0
field = [
    "......",
    "D.....",
    "D.....",
    "......"
]
precondition = [[1, 2], [1, 3]]

[[book]]
name = "LTR-HEAD"
score = 8.6
field = [
    "D.....",
    "DBAC..",
    "DBBA..",
    "AAAC.."
]

[[book]]
name = "LTR-HEAD"
score = 8.6
field = [
    "B.....",
    "D.....",
    "E.....",
    "ED....",
    "DBAC..",
    "DBBA..",
    "AAAC.."
]

[[book]]
name = "LTR-HEAD"
score = 8.6
field = [
    "b.....",
    "B.....",
    "Dd....",
    "Dd....",
    "Tt....",
    "Tt....",
    "DBAC..",
    "DBBA..",
    "AAAC.."
]

[[book]]
name = "LTR-HEAD"
score = 8.6
field = [
    "b.....",
    "Bb....",
    "Dd....",
    "T.....",
    "Td....",
    "TDd...",
    "DBAC..",
    "DBBA..",
    "AAAC.."
]
