# A = should be A, neighbors will be checked.
# a = A is allowed, neighbors won't be checked.
# * = anything allowed
# For more information, see book_field_test.cc for examples.

[[book]]
field = [
    "BBA...",
    "AAC..."
]
name = "GTR-BASE"
score = 10.300000

[[book]]
name = "GTR-KEY"
score = 11.0
field = [
    "B.....",
    "......",
    "......"
]

[[book]]
field = [
    "bDD...",
    "BEE...",
    "DDE...",
    "BAC...",
    "BBA...",
    "AAC..."
]
name = "GTR-HEAD"
score = 9.000000

[[book]]
field = [
    ".D....",
    "bD....",
    "BEE...",
    "DDE...",
    "BAC...",
    "BBA...",
    "AAC..."
]
name = "GTR-HEAD"
score = 9.000000

[[book]]
field = [
    "b.....",
    "BD....",
    "DD....",
    "BAC...",
    "BBA...",
    "AAC..."
]
name = "GTR-HEAD"
score = 10.000000

[[book]]
field = [
    "b.....",
    "Bb....",
    "D.....",
    "DD....",
    "BAC...",
    "BBA...",
    "AAC..."
]
name = "GTR-HEAD"
score = 10.000000

[[book]]
field = [
    "b.....",
    "Bb....",
    "DDD...",
    "BAC...",
    "BBA...",
    "AAC..."
]
name = "GTR-HEAD"
score = 10.000000

[[book]]
field = [
    "b.....",
    "B.....",
    "DD....",
    "DE....",
    "BAC...",
    "BBA...",
    "AAC..."
]
name = "GTR-HEAD"
score = 9.000000

[[book]]
field = [
    "B.....",
    "E.....",
    "E.....",
    "E.....",
    "DD....",
    "DE....",
    "BAC...",
    "BBA...",
    "AAC..."
]
name = "GTR-HEAD"
score = 9.000000

[[book]]
name = "GTR-HEAD"
score = 8.000000
field = [
    "B.....",
    "B.....",
    "D.....",
    "DAC...",
    "BBA...",
    "AAC..."
]

[[book]]
field = [
    "....YY",
    "..CYXY",
    "...CCC",
    "..CXXX"
]
name = "GTR-TAIL"
score = 9.800000

[[book]]
field = [
    "..C...",
    "..CXYX",
    "...CXX",
    "..CYYY"
]
name = "GTR-TAIL"
score = 9.500000

[[book]]
field = [
    "....Y.",
    "..CYXY",
    "...CCX",
    "..CXXY"
]
name = "GTR-TAIL"
score = 9.000000

[[book]]
field = [
    "....YY",
    "..CXXX",
    "...CCC",
    "..CYYX"
]
name = "GTR-TAIL"
score = 9.800000

[[book]]
field = [
    ".....Y",
    ".....Y",
    "..CXXX",
    "...CCC",
    "..CYYX"
]
name = "GTR-TAIL"
score = 9.800000

[[book]]
field = [
    ".....Y",
    "....YZ",
    "..CXXX",
    "...CCC",
    "..CYYX"
]
name = "GTR-TAIL"
score = 9.800000

[[book]]
field = [
    ".....y",
    "...xxY",
    "..CXXY",
    "...CCX",
    "..CYYX"
]
name = "GTR-TAIL"
score = 9.900000

[[book]]
field = [
    "....Y.",
    "..CYXY",
    "...CCY",
    "..CXXX"
]
name = "GTR-TAIL"
score = 9.700000

[[book]]
field = [
    ".....y",
    ".....Y",
    "..CXXY",
    "...YYX",
    "..CCCX"
]
name = "GTR-TAIL"
score = 9.900000

[[book]]
field = [
    "....yy",
    "...*YY",
    "..CXXZ",
    "...YYX",
    "..CCCX"
]
name = "GTR-TAIL"
score = 9.800000

[[book]]
field = [
    "...x.Y",
    "..CXYY",
    "...CXX",
    "..CCXY"
]
name = "GTR-TAIL"
score = 9.900000

[[book]]
field = [
    "...x..",
    "..xXxY",
    "..CZYY",
    "...CXX",
    "..CCXY"
]
name = "GTR-TAIL"
score = 9.900000

[[book]]
field = [
    "...xy.",
    "..xXYy",
    "..CXYZ",
    "...CXY",
    "..CCXY"
]
name = "GTR-TAIL"
score = 9.700000

[[book]]
field = [
    "...xyz",
    "..xXYZ",
    "..CXZY",
    "...CXY",
    "..CCXY"
]
name = "GTR-TAIL"
score = 9.800000

[[book]]
name = "GTR-TAIL"
score = 8.800000
field = [
    ".....Z",
    "..CXYZ",
    "..CCYZ",
    "...XXY",
    "..CXZY"
]

[[book]]
field = [
    "a.....",
    "A.....",
    "Bb....",
    "DD....",
    "BDC...",
    "BAA...",
    "BAC..."
]
name = "LR-HEAD"
score = 9.700000

[[book]]
field = [
    "a.....",
    "A.....",
    "B.....",
    "A.....",
    "AA....",
    "BDC...",
    "BAA...",
    "BAC..."
]
name = "LR-HEAD"
score = 9.500000

[[book]]
field = [
    "a.....",
    "A.....",
    "B.....",
    "B.....",
    "A.....",
    "AA....",
    "BDC...",
    "BAA...",
    "BAC..."
]
name = "LR-HEAD"
score = 9.400000

[[book]]
field = [
    "ad....",
    "AD....",
    "BEE...",
    "DED...",
    "BDC...",
    "BAA...",
    "BAC..."
]
name = "LR-HEAD"
score = 8.000000

[[book]]
field = [
    "b.....",
    "B.....",
    "EEE...",
    "BAD...",
    "BBA...",
    "AAC..."
]
name = "GTR2-HEAD"
score = 10.000000

[[book]]
field = [
    "b.....",
    "Bb....",
    "EEE...",
    "BAD...",
    "BBA...",
    "AAC..."
]
name = "GTR2-HEAD"
score = 10.000000

[[book]]
field = [
    "b.....",
    "BE....",
    "EE....",
    "BAD...",
    "BBA...",
    "AAC..."
]
name = "GTR2-HEAD"
score = 10.000000

[[book]]
field = [
    "b.....",
    "B.....",
    "E.....",
    "EE....",
    "BAD...",
    "BBA...",
    "AAC..."
]
name = "GTR2-HEAD"
score = 10.000000

[[book]]
field = [
    ".....c",
    "....cC",
    "..DXXX",
    "...DDD",
    "..CCCX"
]
name = "GTR2-TAIL"
score = 9.500000

[[book]]
field = [
    "...xXx",
    "..DXCX",
    "...DDD",
    "..CCCX"
]
name = "GTR2-TAIL"
score = 9.500000

[[book]]
field = [
    "..D.X.",
    "...DDD",
    "..CXXX"
]
name = "GTR2-TAIL"
score = 9.500000

[[book]]
name = "GTR2-TAIL"
score = 8.50000
field = [
    ".....Y",
    "....XY",
    "..D.XY",
    "...DDX",
    "..CDYX"
]

[[book]]
name = "GTR2-TAIL"
score = 8.50000
field = [
    ".....Y",
    "....XY",
    "..D.XY",
    "...DYX",
    "..CDDX"
]

[[book]]
field = [
    "BBBA..",
    "AAAC.."
]
name = "NEWGTR-BASE"
score = 10.300000

[[book]]
field = [
    "......",
    "..A...",
    "BBBA..",
    "AAAC.."
]
name = "NEWGTR"
score = 10.200000

[[book]]
field = [
    ".b....",
    "DBb...",
    "DDAC..",
    "BBBA..",
    "AAAC.."
]
name = "NEWGTR-HEAD"
score = 10.000000

[[book]]
field = [
    "De....",
    "EEe...",
    "DBb...",
    "DDAC..",
    "BBBA..",
    "AAAC.."
]
name = "NEWGTR-HEAD"
score = 10.000000

[[book]]
field = [
    "BD....",
    "DDAC..",
    "BBBA..",
    "AAAC.."
]
name = "NEWGTR-HEAD"
score = 10.000000

[[book]]
field = [
    "b.....",
    "Bb....",
    "D.....",
    "DDAC..",
    "BBBA..",
    "AAAC.."
]
name = "NEWGTR-HEAD"
score = 10.100000

[[book]]
field = [
    "b.....",
    "Bb....",
    "E.....",
    "D.....",
    "DEE...",
    "DEAC..",
    "BBBA..",
    "AAAC.."
]
name = "NEWGTR-HEAD"
score = 9.800000

[[book]]
field = [
    "b.....",
    "B.....",
    "E.....",
    "E.....",
    "E.....",
    "DD....",
    "DEAC..",
    "BBBA..",
    "AAAC.."
]
name = "NEWGTR-HEAD"
score = 9.800000

[[book]]
name = "NEWGTR-HEAD"
score = 8.000000
field = [
    ".D....",
    "BD....",
    "DEE...",
    "DEAC..",
    "BBBA..",
    "AAAC.."
]

[[book]]
name = "NEWGTR-HEAD"
score = 9.700000
field = [
    "B.....",
    "D.....",
    "D.....",
    "E.....",
    "DEE...",
    "DFAC..",
    "BBBA..",
    "AAAC.."
]

[[book]]
name = "NEWGTR-TAIL"
score = 10.000000
field = [
    ".....x",
    "...cxX",
    "...CxX",
    "....CC",
    "...CXX"
]

[[book]]
name = "NEWGTR-TAIL"
score = 10.000000
field = [
    "...c.X",
    "...CXX",
    "....CC",
    "...CYX"
]

[[book]]
name = "NEWGTR-TAIL"
score = 9.800000
field = [
    "...c.X",
    "...CXX",
    "....CC",
    "...CXC"
]

[[book]]
name = "NEWGTR-TAIL"
score = 9.000000
field = [
    "...cxx",
    "...CXX",
    "....CC",
    "...CXX"
]

[[book]]
name = "NEWGTR-TAIL"
score = 9.000000
field = [
    ".....Y",
    "...CXY",
    "...CXY",
    "....CX",
    "...CXY"
]

[[book]]
name = "NEWGTR-TAIL"
score = 9.000000
field = [
    ".....Y",
    "...CXY",
    "...CXX",
    "....CY",
    "...CXY"
]

[[book]]
name = "NEWGTR-TAIL"
score = 7.000000
field = [
    ".....Y",
    "...CXY",
    "...CXY",
    "....YX",
    "...CCX"
]

[[book]]
name = "NEWGTR-TAIL"
score = 7.000000
field = [
    ".....Y",
    "...CXY",
    "...CYX",
    "....YX",
    "...CCX"
]

[[book]]
name = "NEWGTR-TAIL"
score = 9.000000
field = [
    ".....y",
    "....yY",
    "....YX",
    "...CXX",
    "....CC",
    "...CXY"
]

[[book]]
name = "NEWGTR2-HEAD"
score = 10.000000
field = [
    ".b....",
    "DBb...",
    "DDAE..",
    "BBBA..",
    "AAAC.."
]

[[book]]
field = [
    "b.....",
    "Bb....",
    "D.....",
    "DDAE..",
    "BBBA..",
    "AAAC.."
]
name = "NEWGTR2-HEAD"
score = 10.000000

[[book]]
field = [
    "b.....",
    "BD....",
    "DDAE..",
    "BBBA..",
    "AAAC.."
]
name = "NEWGTR2-HEAD"
score = 10.000000

[[book]]
field = [
    "B.....",
    "DD....",
    "DFAE..",
    "BBBA..",
    "AAAC.."
]
name = "NEWGTR2-HEAD"
score = 10.000000

[[book]]
field = [
    "b.....",
    "B.....",
    "F.....",
    "F.....",
    "F.....",
    "DD....",
    "DFAE..",
    "BBBA..",
    "AAAC.."
]
name = "NEWGTR2-HEAD"
score = 10.000000

[[book]]
field = [
    "b.....",
    "B.....",
    "F.....",
    "F.....",
    "D.....",
    "DFf...",
    "DFAE..",
    "BBBA..",
    "AAAC.."
]
name = "NEWGTR2-HEAD"
score = 10.000000

[[book]]
field = [
    "B.....",
    "D.....",
    "D.....",
    "G.....",
    "DGG...",
    "DFAE..",
    "BBBA..",
    "AAAC.."
]
name = "NEWGTR2-HEAD"
score = 9.700000

[[book]]
name = "NEWGTR2-HEAD"
score = 9.700000
field = [
    "B.....",
    "D.....",
    "D.....",
    "GG....",
    "DG....",
    "DFAE..",
    "BBBA..",
    "AAAC.."
]

[[book]]
field = [
    "...E..",
    "....EE",
    "...CEX"
]
name = "NEWGTR2-TAIL"
score = 9.500000

[[book]]
field = [
    "....cc",
    "...ECC",
    "....EE",
    "...CEC"
]
name = "NEWGTR2-TAIL"
score = 9.800000

[[book]]
field = [
    "...e..",
    "...ECE",
    "....EE",
    "...CCC"
]
name = "NEWGTR2-TAIL"
score = 9.800000

[[book]]
name = "NEWGTR2-TAIL"
score = 9.800000
field = [
    ".....X",
    "...XCX",
    "...EXE",
    "....EE",
    "...CCC"
]

[[book]]
field = [
    "...ecc",
    "...ECC",
    "....EE",
    "...CCE"
]
name = "NEWGTR2-TAIL"
score = 9.800000

[[book]]
field = [
    "....xc",
    "...*XC",
    "...ECX",
    "....EE",
    "...CCE"
]
name = "NEWGTR2-TAIL"
score = 9.800000

[[book]]
field = [
    "....xX",
    "...EXE",
    "....EE",
    "...CXX"
]
name = "NEWGTR2-TAIL"
score = 8.200000

[[book]]
name = "NEWGTR2-TAIL"
score = 8.0
field = [
    ".....X",
    "...EXX",
    "...ECC",
    "....EE",
    "...CCX"
]

[[book]]
field = [
    "D.....",
    "DBAC..",
    "DBBA..",
    "AAAC.."
]
name = "LTR-HEAD"
score = 9.600000

[[book]]
field = [
    "b.....",
    "B.....",
    "Dd....",
    "Dd....",
    "Tt....",
    "Tt....",
    "DBAC..",
    "DBBA..",
    "AAAC.."
]
name = "LTR-HEAD"
score = 9.600000

[[book]]
field = [
    "b.....",
    "Bb....",
    "Dd....",
    "T.....",
    "Td....",
    "TDd...",
    "DBAC..",
    "DBBA..",
    "AAAC.."
]
name = "LTR-HEAD"
score = 9.600000

[[book]]
field = [
    "DDAC..",
    "DBBA..",
    "BAAC.."
]
name = "FUKIGENGTR-HEAD"
score = 9.900000

[[book]]
field = [
    "D.....",
    "DbAC..",
    "DBBA..",
    "BAAC.."
]
name = "FUKIGENGTR-HEAD"
score = 9.800000

[[book]]
field = [
    "b.....",
    "Bb....",
    "DDAE..",
    "DBBA..",
    "BAAC.."
]
name = "FUKIGENGTR2-HEAD"
score = 9.800000

# ----------------------------------------------------------------------

[[book]]
field = [
    "b.....",
    "Bb....",
    "DDD...",
    "BAC...",
    "BBE...",
    "AAA..."
]
name = "ZABUTONL-HEAD"
score = 9.200000

[[book]]
field = [
    "b.....",
    "BD....",
    "DD....",
    "BAC...",
    "BBE...",
    "AAA..."
]
name = "ZABUTONL-HEAD"
score = 9.100000

[[book]]
name = "ZABUTONL-HEAD"
score = 9.100000
field = [
    "b.....",
    "Bb....",
    "D.....",
    "DD....",
    "BAC...",
    "BBE...",
    "AAA..."
]

[[book]]
name = "ZABUTONL-HEAD"
score = 8.900000
field = [
    "b.....",
    "B.....",
    "DD....",
    "DF*...",
    "BAC...",
    "BBE...",
    "AAA..."
]

[[book]]
field = [
    "BAC...",
    "BBECC.",
    "AAAFC."
]
name = "ZABUTONL-TAIL"
score = 9.000000

[[book]]
field = [
    "BACXXx",
    "BBECCC",
    "AAAFXX"
]
name = "ZABUTONL-TAIL"
score = 9.000000

[[book]]
field = [
    "BACXXx",
    "BBECCC",
    "AAAFXX"
]
name = "ZABUTONL-TAIL"
score = 9.000000

[[book]]
field = [
    "..c...",
    "BACcX.",
    "BBEXEX",
    "AAAEEX"
]
name = "ZABUTONL-TAIL"
score = 9.000000

# ----------------------------------------------------------------------

[[book]]
field = [
    "e.....",
    "E*c.d.",
    "EBCdD.",
    "AABCCD",
    "ABBCDD"
]
name = "DAAZUMI"
score = 9.800000

[[book]]
field = [
    "e.....",
    "E*cd..",
    "EBCDd.",
    "AABCCD",
    "ABBCDD"
]
name = "DAAZUMI"
score = 9.800000

[[book]]
field = [
    "B.....",
    "A.....",
    "B.....",
    "B.....",
    "E.....",
    "E.....",
    "BE....",
    "BBCdd.",
    "AABCCD",
    "ABBCDD"
]
name = "DAAZUMI"
score = 9.8

# ----------------------------------------------------------------------

[[book]]
field = [
    "ACBD..",
    "AACB.D",
    "BBCCDD"
]
name = "LLR"
score = 9.300000

[[book]]
field = [
    "..bd..",
    "ACBDd.",
    "AACC.D",
    "BBCBDD"
]
name = "LLR"
score = 9.300000

[[book]]
field = [
    "..bb..",
    "ACBBb.",
    "AACD.D",
    "BBCCDD"
]
name = "LLR"
score = 9.300000

[[book]]
field = [
    "a.....",
    "Aa....",
    "Bb....",
    "DD....",
    "DAC...",
    "BAA...",
    "BBC..."
]
name = "NAMEKUJI"
score = 5.200000

[[book]]
field = [
    "a.....",
    "Aa....",
    "Bb....",
    "DD....",
    "DAC...",
    "BAA...",
    "BBC..."
]
name = "NAMEKUJI"
score = 5.200000

[[book]]
field = [
    "EC....",
    "EEDAbb",
    "CCCDDD",
    "AAABBB"
]
name = "YAYOI"
score = 9.000000

[[book]]
field = [
    "CE....",
    "EEDAbb",
    "CCCDDD",
    "AAABBB"
]
name = "YAYOI"
score = 8.800000

# ----------------------------------------------------------------------

[[book]]
name = "DOUSHOKU"
score = 9.0
field = [
    "....EE",
    "BAAEDE",
    "BBCAAA",
    "AAADDD"
]

[[book]]
name = "DOUSHOKU"
score = 8.9
field = [
    "A.....",
    "B.....",
    "B.....",
    "X...EE",
    "XXAEDE",
    "BBCAAA",
    "AAADDD"
]

[[book]]
name = "DOUSHOKU"
score = 8.9
field = [
    "A.....",
    "B.....",
    "XX..EE",
    "BXAEDE",
    "BBCAAA",
    "AAADDD"
]

# ----------------------------------------------------------------------

[[combine]]
name = "GTR"
combine = ["GTR-BASE", "GTR-KEY", "GTR-HEAD", "GTR-TAIL"]

[[combine]]
name = "GTR"
combine = ["GTR-BASE", "GTR-KEY", "GTR2-HEAD", "GTR2-TAIL"]

[[combine]]
name = "NEWGTR"
combine = ["NEWGTR", "NEWGTR-BASE", "NEWGTR-HEAD", "NEWGTR-TAIL"]

[[combine]]
name = "NEWGTR"
combine = ["NEWGTR", "NEWGTR-BASE", "NEWGTR2-HEAD", "NEWGTR2-TAIL"]

[[combine]]
name = "LR-HEAD"
combine = ["LR-HEAD", "GTR-TAIL"]

[[combine]]
name = "LTR-HEAD"
combine = ["LTR-HEAD", "NEWGTR-TAIL"]

[[combine]]
name = "FUKIGENGTR-HEAD"
combine = ["FUKIGENGTR-HEAD", "NEWGTR-TAIL"]

[[combine]]
name = "FUKIGENGTR2-HEAD"
combine = ["FUKIGENGTR2-HEAD", "NEWGTR2-TAIL"]

[[combine]]
name = "ZABUTONL-HEAD"
combine = ["ZABUTONL-HEAD","ZABUTONL-TAIL"]

[[combine]]
name = "DAAZUMI"
combine = ["DAAZUMI"]

[[combine]]
name = "LLR"
combine = ["LLR"]

[[combine]]
name = "NAMEKUJI"
combine = ["NAMEKUJI", "GTR-TAIL"]

[[combine]]
name = "YAYOI"
combine = ["YAYOI"]

[[combine]]
name = "DOUSHOKU"
combine = ["DOUSHOKU"]
