# A = should be A, neighbors will be checked.
# a = A is allowed, neighbors won't be checked.
# * = anything allowed
# For more information, see book_field_test.cc for examples.

[[book]]
field = [
    "BBA...",
    "AAC..."
]
name = "GTR-BASE"
score = 10.3

[[book]]
name = "GTR-KEY"
score = 11.0
field = [
    "B.....",
    "......",
    "......"
]

[[book]]
name = "GTR-HEAD"
score = 9.0
field = [
    "bDD...",
    "BEE...",
    "DDE...",
    "BAC...",
    "BBA...",
    "AAC..."
]

[[book]]
field = [
    ".D....",
    "bD....",
    "BEE...",
    "DDE...",
    "BAC...",
    "BBA...",
    "AAC..."
]
name = "GTR-HEAD"
score = 9.0

[[book]]
field = [
    "b.....",
    "BD....",
    "DD....",
    "BAC...",
    "BBA...",
    "AAC..."
]
name = "GTR-HEAD"
score = 10.0

[[book]]
field = [
    "b.....",
    "Bb....",
    "D.....",
    "DD....",
    "BAC...",
    "BBA...",
    "AAC..."
]
name = "GTR-HEAD"
score = 10.0

[[book]]
field = [
    "b.....",
    "Bb....",
    "DDD...",
    "BAC...",
    "BBA...",
    "AAC..."
]
name = "GTR-HEAD"
score = 10.0

[[book]]
field = [
    "b.....",
    "B.....",
    "DD....",
    "DE....",
    "BAC...",
    "BBA...",
    "AAC..."
]
name = "GTR-HEAD"
score = 9.0

[[book]]
field = [
    "B.....",
    "E.....",
    "E.....",
    "E.....",
    "DD....",
    "DE....",
    "BAC...",
    "BBA...",
    "AAC..."
]
name = "GTR-HEAD"
score = 9.0

[[book]]
name = "GTR-HEAD"
score = 8.0
field = [
    "B.....",
    "B.....",
    "D.....",
    "DAC...",
    "BBA...",
    "AAC..."
]

[[book]]
name = "GTR-TAIL"
score = 9.8
field = [
    "....YY",
    "..CYXY",
    "...CCC",
    "..CXXX"
]

[[book]]
name = "GTR-TAIL"
score = 8.8
field = [
    "..C...",
    "..CXYX",
    "...CXX",
    "..CYYY"
]

[[book]]
name = "GTR-TAIL"
score = 7.2
field = [
    ".....Z",
    "..CXYZ",
    "..CXYZ",
    "...CXY",
    "..CXYZ"
]

[[book]]
name = "GTR-TAIL"
score = 7.2
field = [
    ".....Z",
    "..CXYZ",
    "..CXXZ",
    "...CYY",
    "..CXYZ"
]

[[book]]
name = "GTR-TAIL"
score = 7.2
field = [
    ".....Z",
    "..CXYZ",
    "..CXYY",
    "...CXZ",
    "..CXYZ"
]

[[book]]
name = "GTR-TAIL"
score = 9.2
field = [
    "......",
    "..C.YY",
    "..CXZY",
    "...CXX",
    "..CZXY"
]

[[book]]
field = [
    "....Y.",
    "..CYXY",
    "...CCX",
    "..CXXY"
]
name = "GTR-TAIL"
score = 9.0

[[book]]
field = [
    "....YY",
    "..CXXX",
    "...CCC",
    "..CYYX"
]
name = "GTR-TAIL"
score = 9.8

[[book]]
field = [
    ".....Y",
    ".....Y",
    "..CXXX",
    "...CCC",
    "..CYYX"
]
name = "GTR-TAIL"
score = 9.8

[[book]]
field = [
    ".....Y",
    "....YZ",
    "..CXXX",
    "...CCC",
    "..CYYX"
]
name = "GTR-TAIL"
score = 9.8

[[book]]
field = [
    ".....y",
    "...xxY",
    "..CXXY",
    "...CCX",
    "..CYYX"
]
name = "GTR-TAIL"
score = 9.9

[[book]]
field = [
    "....Y.",
    "..CYXY",
    "...CCY",
    "..CXXX"
]
name = "GTR-TAIL"
score = 9.7

[[book]]
field = [
    ".....y",
    ".....Y",
    "..CXXY",
    "...YYX",
    "..CCCX"
]
name = "GTR-TAIL"
score = 9.9

[[book]]
name = "GTR-TAIL"
score = 8.9
field = [
    "....XY",
    "..C.YX",
    "...YYX",
    "..CCCX"
]

[[book]]
name = "GTR-TAIL"
score = 8.9
field = [
    ".....Z",
    "....ZY",
    "....XY",
    "..CZYX",
    "...ZYX",
    "..CCCX"
]

[[book]]
name = "GTR-TAIL"
score = 8.5
field = [
    "....XY",
    "..C.XY",
    "...YYX",
    "..CCCX"
]

[[book]]
field = [
    "....yy",
    "...*YY",
    "..CXXZ",
    "...YYX",
    "..CCCX"
]
name = "GTR-TAIL"
score = 9.8

[[book]]
field = [
    "...x.Y",
    "..CXYY",
    "...CXX",
    "..CCXY"
]
name = "GTR-TAIL"
score = 9.9

[[book]]
field = [
    "...x..",
    "..xXxY",
    "..CZYY",
    "...CXX",
    "..CCXY"
]
name = "GTR-TAIL"
score = 9.9

[[book]]
field = [
    "...xy.",
    "..xXYy",
    "..CXYZ",
    "...CXY",
    "..CCXY"
]
name = "GTR-TAIL"
score = 9.7

[[book]]
field = [
    "...xyz",
    "..xXYZ",
    "..CXZY",
    "...CXY",
    "..CCXY"
]
name = "GTR-TAIL"
score = 9.8

[[book]]
name = "GTR-TAIL"
score = 8.8
field = [
    ".....Z",
    "..CXYZ",
    "..CCYZ",
    "...XXY",
    "..CXZY"
]

[[book]]
name = "GTR-TAIL"
score = 6.8
field = [
    "....Xy",
    "..CXXY",
    "...CCX",
    "..CYYY"
]

# ----------------------------------------------------------------------
[[book]]
name = "LR-KEY"
score = 1.0
field = [
    "B.....",
    "B.....",
    "B.....",
]
precondition = [[1, 1], [1, 2], [1, 3]]

[[book]]
name = "LR-HEAD"
score = 9.7
field = [
    "a.....",
    "A.....",
    "Bb....",
    "DD....",
    "BDC...",
    "BAA...",
    "BAC..."
]

[[book]]
name = "LR-HEAD"
score = 9.5
field = [
    "a.....",
    "A.....",
    "B.....",
    "A.....",
    "AA....",
    "BDC...",
    "BAA...",
    "BAC..."
]

[[book]]
field = [
    "a.....",
    "A.....",
    "B.....",
    "B.....",
    "A.....",
    "AA....",
    "BDC...",
    "BAA...",
    "BAC..."
]
name = "LR-HEAD"
score = 9.4

[[book]]
field = [
    "ad....",
    "AD....",
    "BEE...",
    "DED...",
    "BDC...",
    "BAA...",
    "BAC..."
]
name = "LR-HEAD"
score = 8.0

# ----------------------------------------------------------------------

[[book]]
field = [
    "b.....",
    "B.....",
    "EEE...",
    "BAD...",
    "BBA...",
    "AAC..."
]
name = "GTR2-HEAD"
score = 10.0

[[book]]
field = [
    "b.....",
    "Bb....",
    "EEE...",
    "BAD...",
    "BBA...",
    "AAC..."
]
name = "GTR2-HEAD"
score = 10.0

[[book]]
field = [
    "b.....",
    "BE....",
    "EE....",
    "BAD...",
    "BBA...",
    "AAC..."
]
name = "GTR2-HEAD"
score = 10.0

[[book]]
field = [
    "b.....",
    "B.....",
    "E.....",
    "EE....",
    "BAD...",
    "BBA...",
    "AAC..."
]
name = "GTR2-HEAD"
score = 10.0

[[book]]
field = [
    ".....c",
    "....cC",
    "..DXXX",
    "...DDD",
    "..CCCX"
]
name = "GTR2-TAIL"
score = 9.5

[[book]]
field = [
    "...xXx",
    "..DXCX",
    "...DDD",
    "..CCCX"
]
name = "GTR2-TAIL"
score = 9.5

[[book]]
field = [
    "..D.X.",
    "...DDD",
    "..CXXX"
]
name = "GTR2-TAIL"
score = 9.5

[[book]]
name = "GTR2-TAIL"
score = 8.50000
field = [
    ".....Y",
    "....XY",
    "..D.XY",
    "...DDX",
    "..CDYX"
]

[[book]]
name = "GTR2-TAIL"
score = 8.50000
field = [
    ".....Y",
    "....XY",
    "..D.XY",
    "...DYX",
    "..CDDX"
]

# ----------------------------------------------------------------------

[[book]]
field = [
    "..A...",
    "BBBA..",
    "AAAC.."
]
name = "NEWGTR-BASE"
score = 10.3

[[book]]
field = [
    ".b....",
    "DBb...",
    "DDAC..",
    "BBBA..",
    "AAAC.."
]
name = "NEWGTR-HEAD"
score = 10.0

[[book]]
field = [
    "De....",
    "EEe...",
    "DBb...",
    "DDAC..",
    "BBBA..",
    "AAAC.."
]
name = "NEWGTR-HEAD"
score = 10.0

[[book]]
field = [
    "BD....",
    "DDAC..",
    "BBBA..",
    "AAAC.."
]
name = "NEWGTR-HEAD"
score = 8.2

[[book]]
name = "NEWGTR-HEAD"
score = 8.2
field = [
    "B.....",
    "D.....",
    "EE....",
    "ED....",
    "DDAC..",
    "BBBA..",
    "AAAC.."
]

[[book]]
field = [
    "b.....",
    "Bb....",
    "D.....",
    "DDAC..",
    "BBBA..",
    "AAAC.."
]
name = "NEWGTR-HEAD"
score = 10.1

[[book]]
field = [
    "b.....",
    "Bb....",
    "E.....",
    "D.....",
    "DEE...",
    "DEAC..",
    "BBBA..",
    "AAAC.."
]
name = "NEWGTR-HEAD"
score = 8.8

[[book]]
name = "NEWGTR-HEAD"
score = 9.2
field = [
    "b.....",
    "B.....",
    "E.....",
    "E.....",
    "E.....",
    "DD....",
    "DEAC..",
    "BBBA..",
    "AAAC.."
]

[[book]]
name = "NEWGTR-HEAD"
score = 8.0
field = [
    ".D....",
    "BD....",
    "DEE...",
    "DEAC..",
    "BBBA..",
    "AAAC.."
]

[[book]]
name = "NEWGTR-HEAD"
score = 9.7
field = [
    "B.....",
    "D.....",
    "D.....",
    "E.....",
    "DEE...",
    "DFAC..",
    "BBBA..",
    "AAAC.."
]

[[book]]
name = "NEWGTR-HEAD"
score = 9.6
field = [
    "B.....",
    "D.....",
    "D.....",
    "E.....",
    "EE....",
    "DDAC..",
    "BBBA..",
    "AAAC.."
]

[[book]]
name = "NEWGTR-TAIL"
score = 10.0
field = [
    ".....x",
    "...cxX",
    "...CxX",
    "....CC",
    "...CXX"
]

[[book]]
name = "NEWGTR-TAIL"
score = 10.0
field = [
    "...c.X",
    "...CXX",
    "....CC",
    "...CYX"
]

[[book]]
name = "NEWGTR-TAIL"
score = 9.8
field = [
    "...c.X",
    "...CXX",
    "....CC",
    "...CXC"
]

[[book]]
name = "NEWGTR-TAIL"
score = 9.0
field = [
    "...cxx",
    "...CXX",
    "....CC",
    "...CXX"
]

[[book]]
name = "NEWGTR-TAIL"
score = 9.0
field = [
    ".....Y",
    "...CXY",
    "...CXY",
    "....CX",
    "...CXY"
]

[[book]]
name = "NEWGTR-TAIL"
score = 9.0
field = [
    ".....Y",
    "...CXY",
    "...CXX",
    "....CY",
    "...CXY"
]

[[book]]
name = "NEWGTR-TAIL"
score = 2.0
field = [
    ".....Y",
    "...CXY",
    "...CXY",
    "....YX",
    "...CCX"
]

[[book]]
name = "NEWGTR-TAIL"
score = 2.0
field = [
    ".....Y",
    "...CXY",
    "...CYX",
    "....YX",
    "...CCX"
]

[[book]]
name = "NEWGTR-TAIL"
score = 9.0
field = [
    ".....y",
    "....yY",
    "....YX",
    "...CXX",
    "....CC",
    "...CXY"
]

[[book]]
name = "NEWGTR-TAIL"
score = 9.0
field = [
    "....X.",
    "...CX.",
    "....CX",
    "...CCX"
]

[[book]]
name = "NEWGTR-TAIL"
score = 9.0
field = [
    ".....Y",
    ".....Y",
    "....XY",
    "...CYX",
    "....CX",
    "...CCX"
]

[[book]]
name = "NEWGTR-TAIL"
score = 8.8
field = [
    "....YY",
    "....XY",
    "...CYX",
    "....CX",
    "...CCX"
]

# ----------------------------------------------------------------------

[[book]]
name = "NEWGTR2-HEAD"
score = 10.0
field = [
    ".b....",
    "DBb...",
    "DDAE..",
    "BBBA..",
    "AAAC.."
]

[[book]]
field = [
    "b.....",
    "Bb....",
    "D.....",
    "DDAE..",
    "BBBA..",
    "AAAC.."
]
name = "NEWGTR2-HEAD"
score = 10.0

[[book]]
field = [
    "b.....",
    "BD....",
    "DDAE..",
    "BBBA..",
    "AAAC.."
]
name = "NEWGTR2-HEAD"
score = 10.0

[[book]]
field = [
    "B.....",
    "DD....",
    "DFAE..",
    "BBBA..",
    "AAAC.."
]
name = "NEWGTR2-HEAD"
score = 10.0

[[book]]
field = [
    "b.....",
    "B.....",
    "F.....",
    "F.....",
    "F.....",
    "DD....",
    "DFAE..",
    "BBBA..",
    "AAAC.."
]
name = "NEWGTR2-HEAD"
score = 10.0

[[book]]
field = [
    "b.....",
    "B.....",
    "F.....",
    "F.....",
    "D.....",
    "DFf...",
    "DFAE..",
    "BBBA..",
    "AAAC.."
]
name = "NEWGTR2-HEAD"
score = 10.0

[[book]]
field = [
    "B.....",
    "D.....",
    "D.....",
    "G.....",
    "DGG...",
    "DFAE..",
    "BBBA..",
    "AAAC.."
]
name = "NEWGTR2-HEAD"
score = 9.7

[[book]]
name = "NEWGTR2-HEAD"
score = 9.7
field = [
    "B.....",
    "D.....",
    "D.....",
    "GG....",
    "DG....",
    "DFAE..",
    "BBBA..",
    "AAAC.."
]

[[book]]
field = [
    "...E..",
    "....EE",
    "...CEX"
]
name = "NEWGTR2-TAIL"
score = 9.5

[[book]]
field = [
    "....cc",
    "...ECC",
    "....EE",
    "...CEC"
]
name = "NEWGTR2-TAIL"
score = 9.8

[[book]]
field = [
    "...e..",
    "...ECE",
    "....EE",
    "...CCC"
]
name = "NEWGTR2-TAIL"
score = 7.8

[[book]]
name = "NEWGTR2-TAIL"
score = 8.0
field = [
    ".....X",
    "...XCX",
    "...EXE",
    "....EE",
    "...CCC"
]

[[book]]
field = [
    "...ecc",
    "...ECC",
    "....EE",
    "...CCE"
]
name = "NEWGTR2-TAIL"
score = 9.8

[[book]]
field = [
    "....xc",
    "...*XC",
    "...ECX",
    "....EE",
    "...CCE"
]
name = "NEWGTR2-TAIL"
score = 9.8

[[book]]
field = [
    "....xX",
    "...EXE",
    "....EE",
    "...CXX"
]
name = "NEWGTR2-TAIL"
score = 8.2

[[book]]
name = "NEWGTR2-TAIL"
score = 8.0
field = [
    ".....X",
    "...EXX",
    "...ECC",
    "....EE",
    "...CCX"
]

[[book]]
name = "NEWGTR2-TAIL"
score = 5.0
field = [
    "...EE.",
    "...AAA",
    "...CEE"
]

# ----------------------------------------------------------------------

[[book]]
name = "LTR-KEY"
score = 1.0
field = [
    "......",
    "D.....",
    "D.....",
    "......"
]
precondition = [[1, 2], [1, 3]]

[[book]]
name = "LTR-HEAD"
score = 8.6
field = [
    "D.....",
    "DBAC..",
    "DBBA..",
    "AAAC.."
]

[[book]]
name = "LTR-HEAD"
score = 8.6
field = [
    "B.....",
    "D.....",
    "E.....",
    "ED....",
    "DBAC..",
    "DBBA..",
    "AAAC.."
]

[[book]]
name = "LTR-HEAD"
score = 8.6
field = [
    "b.....",
    "B.....",
    "Dd....",
    "Dd....",
    "Tt....",
    "Tt....",
    "DBAC..",
    "DBBA..",
    "AAAC.."
]

[[book]]
name = "LTR-HEAD"
score = 8.6
field = [
    "b.....",
    "Bb....",
    "Dd....",
    "T.....",
    "Td....",
    "TDd...",
    "DBAC..",
    "DBBA..",
    "AAAC.."
]

# ----------------------------------------------------------------------
# LTR2

[[book]]
name = "LTR2-HEAD"
score = 8.0
field = [
    "D.....",
    "DBAE..",
    "DBBA..",
    "AAAC.."
]

[[book]]
name = "LTR2-HEAD"
score = 8.0
field = [
    "B.....",
    "D.....",
    "D.....",
    "Ff....",
    "Ff....",
    "DBAE..",
    "DBBA..",
    "AAAC.."
]

[[book]]
name = "LTR2-HEAD"
score = 8.0
field = [
    "B.....",
    "D.....",
    "FF....",
    "FD....",
    "DBAE..",
    "DBBA..",
    "AAAC.."
]

# ----------------------------------------------------------------------

[[book]]
field = [
    "DDAC..",
    "DBBA..",
    "BAAC.."
]
name = "FUKIGENGTR-HEAD"
score = 9.9

[[book]]
field = [
    "D.....",
    "DbAC..",
    "DBBA..",
    "BAAC.."
]
name = "FUKIGENGTR-HEAD"
score = 9.8

[[book]]
field = [
    "b.....",
    "Bb....",
    "DDAE..",
    "DBBA..",
    "BAAC.."
]
name = "FUKIGENGTR2-HEAD"
score = 9.8

# ----------------------------------------------------------------------

[[book]]
name = "ZABUTONL-HEAD"
score = 9.2
field = [
    "b.....",
    "Bb....",
    "DDD...",
    "BAC...",
    "BBE...",
    "AAA..."
]

[[book]]
field = [
    "b.....",
    "BD....",
    "DD....",
    "BAC...",
    "BBE...",
    "AAA..."
]
name = "ZABUTONL-HEAD"
score = 9.1

[[book]]
name = "ZABUTONL-HEAD"
score = 9.1
field = [
    "b.....",
    "Bb....",
    "D.....",
    "DD....",
    "BAC...",
    "BBE...",
    "AAA..."
]

[[book]]
name = "ZABUTONL-HEAD"
score = 8.9
field = [
    "b.....",
    "B.....",
    "DD....",
    "DF*...",
    "BAC...",
    "BBE...",
    "AAA..."
]

[[book]]
field = [
    "BAC...",
    "BBECC.",
    "AAAFC."
]
name = "ZABUTONL-TAIL"
score = 9.0

[[book]]
field = [
    "BACXXx",
    "BBECCC",
    "AAAFXX"
]
name = "ZABUTONL-TAIL"
score = 9.0

[[book]]
field = [
    "BACXXx",
    "BBECCC",
    "AAAFXX"
]
name = "ZABUTONL-TAIL"
score = 9.0

[[book]]
field = [
    "..c...",
    "BACcX.",
    "BBEXEX",
    "AAAEEX"
]
name = "ZABUTONL-TAIL"
score = 9.0

# ----------------------------------------------------------------------

[[book]]
field = [
    "e.....",
    "E*c.d.",
    "EBCdD.",
    "AABCCD",
    "ABBCDD"
]
name = "DAAZUMI"
score = 9.8

[[book]]
field = [
    "e.....",
    "E*cd..",
    "EBCDd.",
    "AABCCD",
    "ABBCDD"
]
name = "DAAZUMI"
score = 9.8

[[book]]
field = [
    "B.....",
    "A.....",
    "B.....",
    "B.....",
    "E.....",
    "E.....",
    "BE....",
    "BBCdd.",
    "AABCCD",
    "ABBCDD"
]
name = "DAAZUMI"
score = 9.8

# ----------------------------------------------------------------------

[[book]]
name = "LLR"
score = 9.3
field = [
    "ACBD..",
    "AACB.D",
    "BBCCDD"
]

[[book]]
name = "LLR"
score = 9.3
field = [
    "..bd..",
    "ACBDd.",
    "AACC.D",
    "BBCBDD"
]

[[book]]
name = "LLR"
score = 9.3
field = [
    "..bb..",
    "ACBBb.",
    "AACD.D",
    "BBCCDD"
]

# ----------------------------------------------------------------------

[[book]]
name = "NAMEKUJI-KEY"
score = 10.0
field = [
    "D.....",
    "D.....",
    "......",
    "......"
]

[[book]]
name = "NAMEKUJI-PRECOND"
field = [
    ".AA...",
    "BB...."
]
score = 1.0
precondition = [[1, 1], [2, 1], [2, 2], [3, 2]]

[[book]]
name = "NAMEKUJI"
score = 5.2
field = [
    "a.....",
    "Aa....",
    "Bb....",
    "DD....",
    "DAC...",
    "BAA...",
    "BBC..."
]

[[book]]
name = "NAMEKUJI"
score = 5.2
field = [
    "a.....",
    "Aa....",
    "Bb....",
    "DD....",
    "DAC...",
    "BAA...",
    "BBC..."
]

[[book]]
name = "NAMEKUJI"
score = 5.2
field = [
    "B.....",
    "A.....",
    "D.....",
    "D.....",
    "BB....",
    "DB....",
    "DAC...",
    "BAA...",
    "BBC..."
]

# ----------------------------------------------------------------------

[[book]]
field = [
    "EC....",
    "EEDAbb",
    "CCCDDD",
    "AAABBB"
]
name = "YAYOI"
score = 9.0

[[book]]
field = [
    "CE....",
    "EEDAbb",
    "CCCDDD",
    "AAABBB"
]
name = "YAYOI"
score = 8.8

# ----------------------------------------------------------------------

[[book]]
name = "DOUSHOKU"
score = 9.0
field = [
    "....EE",
    "BAAEDE",
    "BBCAAA",
    "AAADDD"
]

[[book]]
name = "DOUSHOKU"
score = 8.9
field = [
    "A.....",
    "B.....",
    "B.....",
    "X...EE",
    "XXAEDE",
    "BBCAAA",
    "AAADDD"
]

[[book]]
name = "DOUSHOKU"
score = 8.9
field = [
    "A.....",
    "B.....",
    "XX..EE",
    "BXAEDE",
    "BBCAAA",
    "AAADDD"
]

# ----------------------------------------------------------------------

[[combine]]
name = "GTR"
combine = ["GTR-KEY", "GTR-BASE", "GTR-HEAD", "GTR-TAIL"]

[[combine]]
name = "GTR"
combine = ["GTR-KEY", "GTR-BASE", "GTR2-HEAD", "GTR2-TAIL"]

[[combine]]
name = "NEWGTR"
combine = ["NEWGTR-BASE", "NEWGTR-HEAD", "NEWGTR-TAIL"]

[[combine]]
name = "NEWGTR"
combine = ["NEWGTR-BASE", "NEWGTR2-HEAD", "NEWGTR2-TAIL"]

[[combine]]
name = "LR"
combine = ["LR-KEY", "LR-HEAD", "GTR-TAIL"]

[[combine]]
name = "LTR"
combine = ["LTR-KEY", "LTR-HEAD", "NEWGTR-TAIL"]

[[combine]]
name = "LTR"
combine = ["LTR-KEY", "LTR2-HEAD", "NEWGTR2-TAIL"]

[[combine]]
name = "FUKIGEN-GTR"
combine = ["FUKIGENGTR-HEAD", "NEWGTR-TAIL"]

[[combine]]
name = "FUKIGEN-GTR2"
combine = ["FUKIGENGTR2-HEAD", "NEWGTR2-TAIL"]

[[combine]]
name = "ZABUTONL"
combine = ["ZABUTONL-HEAD","ZABUTONL-TAIL"]

[[combine]]
name = "DAAZUMI"
combine = ["DAAZUMI"]

[[combine]]
name = "LLR"
combine = ["LLR"]

[[combine]]
name = "NAMEKUJI"
combine = ["NAMEKUJI-PRECOND", "NAMEKUJI", "NAMEKUJI-KEY", "GTR-TAIL"]

[[combine]]
name = "YAYOI"
combine = ["YAYOI"]

[[combine]]
name = "DOUSHOKU"
combine = ["DOUSHOKU"]
