# ----------------------------------------------------------------------
# GTR-HEAD

[[pattern]]
field = [
    "A.....",
    "AB....",
    "AA....",
    "CB....",
    "BB....",
    "C.....",
    "CC....",
    "......",
]
ignition = 1

[[pattern]]
field = [
    ".A....",
    "BA....",
    "AA....",
    "BC....",
    "BBC...",
    "CC....",
]
ignition = 2

[[pattern]]
field = [
    "......",
    "BA....",
    "AAA...",
    "BC@...",
    "BBC...",
    "CC@...",
]
ignition = 2

[[pattern]]
field = [
    "A.....",
    "ABC...",
    "AABCC.",
    "BBC@@.",
]
ignition = 1

[[pattern]]
field = [
    "A.....",
    "ABC...",
    "AABCCC",
    "BBC@@@",
]
ignition = 1

[[pattern]]
field = [
    "A.C...",
    "ABC...",
    "AABC..",
    "BBC@..",
]
ignition = 1

[[pattern]]
field = [
    "....C.",
    "..B.C.",
    ".AABBC",
    "AAB@@C",
]
ignition = 2

[[pattern]]
field = [
    "..B...",
    "..BC..",
    ".AABCC",
    "AABC@@",
]
ignition = 2

[[pattern]]
field = [
    "..BC..",
    "..BC..",
    ".AABC.",
    "AABC@.",
]
ignition = 2

[[pattern]]
field = [
    ".....C",
    "..AB.C",
    "..AABB",
    "..ABCC",
]
ignition = 3

# ----------------------------------------------------------------------
# GTR-TAIL

[[pattern]]
field = [
    "....C.",
    "...CBC",
    "..AAAC",
    "..ABBB",
]
ignition = 3

[[pattern]]
field = [
    ".....C",
    "...BBC",
    "..AAAB",
    "..ACCB",
]
ignition = 3

[[pattern]]
field = [
    "....CC",
    "...CBC",
    "..AAAA",
    "..ABBB",
]
ignition = 3

[[pattern]]
field = [
    ".....C",
    ".....C",
    ".....B",
    "...CCB",
    "...BBA",
    "...AAA",
]

# ----------------------------------------------------------------------
# NEWGTR-HEAD

[[pattern]]
field = [
    ".A....",
    "BA....",
    "AAC...",
    "BBBC..",
    "CCC@..",
]
ignition = 2

[[pattern]]
field = [
    "A.....",
    "AB....",
    "AAC...",
    "BBBC..",
    "CCC@..",
]
ignition = 1

[[pattern]]
field = [
    "A.BC..",
    "AAABCC",
    "BBBC@@",
]
ignition = 1

[[pattern]]
field = [
    ".ABC..",
    "AAABCC",
    "BBBC@@",
]
ignition = 2

[[pattern]]
field = [
    "A.BC..",
    "AAABC.",
    "BBBCC.",
]
ignition = 1

[[pattern]]
field = [
    ".ABC..",
    "AAABC.",
    "BBBCC.",
]
ignition = 2

# ----------------------------------------------------------------------
# NEWGTR-TAIL

[[pattern]]
field = [
    "....C.",
    "...BC.",
    "..AABC",
    "AAABBC",
]
ignition = 2

[[pattern]]
field = [
    ".....C",
    "...B.C",
    "..AABB",
    "AAABCC",
]
ignition = 2

[[pattern]]
field = [
    ".....C",
    ".....C",
    "....BC",
    "....BB",
    "...AAA",
    "...ABC",
]
ignition = 4

[[pattern]]
field = [
    ".....C",
    ".....C",
    "....CB",
    "....CB",
    "...AAA",
    "...ABB",
]
ignition = 4

# ----------------------------------------------------------------------
# FUKIGEN-GTR

[[pattern]]
field = [
    "BA....",
    "AAC...",
    "ABBC..",
    "BCC@..",
]
ignition = 2

# ----------------------------------------------------------------------
# ZABUTON-L

[[pattern]]
field = [
    "A.....",
    "AB....",
    "AAC.C.",
    "BBBCC."
]
ignition = 1

[[pattern]]
field = [
    "....C.",
    ".ABCBC",
    "AAABBC"
]
ignition = 2
