# ----------------------------------------------------------------------
# GTR

[[pattern]]
field = [
    "..B...",
    "..BC..",
    "..ABC.",
    "AABCC.",
]

[[pattern]]
field = [
    "ABC...",
    "AABCC.",
    "BBC...",
]

[[pattern]]
field = [
    "ABC.D.",
    "AABCCC",
    "BBCDDD",
]

[[pattern]]
field = [
    "....E.",
    "ABCEDE",
    "AABCCE",
    "BBCDDD",
]

[[pattern]]
field = [
    "AF....",
    "FF..EE",
    "ABCEDE",
    "AABCCC",
    "BBCDDD",
]

[[pattern]]
field = [
    "..C...",
    "ABC...",
    "AABC..",
    "BBC...",
]

[[pattern]]
field = [
    "..CD..",
    "ABCD..",
    "AABC..",
    "BBCDD.",
]

[[pattern]]
field = [
    "......",
    "ABC...",
    "AABC..",
    "BBCC..",
]

[[pattern]]
field = [
    "B.....",
    "AAA...",
    "BCD...",
    "BBCD..",
    "CCDD..",
]

[[pattern]]
field = [
    "BA....",
    "AADE..",
    "BCDE..",
    "BBCD..",
    "CCDEE.",
]

[[pattern]]
field = [
    "..C...",
    "ABCDED",
    "AABCDD",
    "BBCEEE",
]

[[pattern]]
field = [
    "..B...",
    "..BCDC",
    "..ABCC",
    "AABDDD",
]

[[pattern]]
field = [
    "ABC...",
    "AABCD.",
    "BBDCC.",
]

[[pattern]]
field = [
    "B.....",
    "AAA...",
    "BC....",
    "BBC...",
    "CC....",
]

[[pattern]]
field = [
    "BA....",
    "AA....",
    "BC....",
    "BBC...",
    "CC....",
]

[[pattern]]
field = [
    "BA....",
    "AA....",
    "BCDE..",
    "BBCDEE",
    "CCDDE.",
]

[[pattern]]
field = [
    "BA....",
    "AA...F",
    "BCDEFF",
    "BBCDEE",
    "CCDDEF",
]

[[pattern]]
field = [
    "BA....",
    "AA....",
    "BCDE..",
    "BBCDE.",
    "CCDDEE",
]

[[pattern]]
field = [
    "B.....",
    "A.....",
    "AA....",
    "BCD...",
    "BBCDD.",
    "CCD...",
]

[[pattern]]
field = [
    "B.....",
    "A.....",
    "AAD...",
    "BCDD..",
    "BBC...",
    "CCD...",
]

[[pattern]]
field = [
    "B.....",
    "A.....",
    "AA....",
    "BCD...",
    "BBCDDD",
    "CC....",
]

[[pattern]]
field = [
    "B.....",
    "B.....",
    "AA....",
    "AC....",
    "BBC...",
    "CC....",
]

[[pattern]]
field = [
    "C.....",
    "B.....",
    "B.....",
    "A.....",
    "BA....",
    "BA....",
    "C.....",
    "CC....",
    "......",
]

[[pattern]]
field = [
    "ABC...",
    "AABCC.",
    "BBC...",
    "......",
    "......",
    "......",
]

# ----------------------------------------------------------------------
# GTR-TAIL

[[pattern]]
field = [
    "C.....",
    "CBB...",
    "BAA...",
    "BCCA..",
]

[[pattern]]
field = [
    "......",
    "..BCC.",
    "..ABBC",
    "AAB..C",
]

# ----------------------------------------------------------------------
# NEWGTR

[[pattern]]
field = [
    "..B...",
    "AAAB..",
    "BBB..."
]

[[pattern]]
field = [
    "..BC..",
    "AAABCC",
    "BBBC..",
]

[[pattern]]
field = [
    ".....D",
    "..BCDD",
    "AAABCC",
    "BBBCD.",
]

[[pattern]]
field = [
    "AB....",
    "AAC...",
    "BBBC..",
    "CCC..."
]

[[pattern]]
field = [
    "AB....",
    "AACD..",
    "BBBCD.",
    "CCCDD."
]

[[pattern]]
field = [
    "AB.D..",
    "AACD..",
    "BBBC..",
    "CCCDD."
]

[[pattern]]
field = [
    "AB...E",
    "AACDEE",
    "BBBCDD",
    "CCCEDE"
]

[[pattern]]
field = [
    "FA....",
    "FF....",
    "BA....",
    "AACD..",
    "BBBCDD",
    "CCCD.."
]

[[pattern]]
field = [
    "AB....",
    "AACD..",
    "BBBCD.",
    "CCCDD."
]

[[pattern]]
field = [
    "AB...E",
    "AACDEE",
    "BBBCDD",
    "CCCEDE"
]

[[pattern]]
field = [
    "B.....",
    "A.....",
    "ABCD..",
    "ABBCDD",
    "CCCD.."
]

[[pattern]]
field = [
    "C.....",
    "B.....",
    "AA....",
    "BA....",
    "BBD...",
    "CCCD..",
    "DDD...",
]

[[pattern]]
field = [
    "C.....",
    "B.....",
    "B.....",
    "A.....",
    "AB....",
    "ABD...",
    "CCCD..",
    "DDD..."
]

[[pattern]]
field = [
    "D.....",
    "CB....",
    "BAA...",
    "BCCA..",
    "BCE...",
    "DDDE..",
    "EEE..."
]

[[pattern]]
field = [
    "D.....",
    "C.....",
    "C.....",
    "CB....",
    "BA....",
    "BAA...",
    "BCE...",
    "DDDE..",
    "EEE..."
]

[[pattern]]
field = [
    "D.....",
    "C.....",
    "CB....",
    "CA....",
    "BA....",
    "BA....",
    "BCE...",
    "DDDE..",
    "EEE..."
]

# ----------------------------------------------------------------------
# LTR

[[pattern]]
field = [
    "CBA...",
    "BAA...",
    "BCD...",
    "BCCD..",
    "DDD..."
]

[[pattern]]
field = [
    "CBA...",
    "BAAE..",
    "BCDE..",
    "BCCDE.",
    "DDDE.."
]

[[pattern]]
field = [
    "CBA...",
    "BAAE..",
    "BCDE..",
    "BCCD..",
    "DDDEE."
]

[[pattern]]
field = [
    "C.....",
    "B..E..",
    "BCDE..",
    "BCCD..",
    "DDDEE."
]

# ----------------------------------------------------------------------
# FUKIGEN-GTR

[[pattern]]
field = [
    "A.....",
    "C.....",
    "C.....",
    "D.....",
    "D.....",
    "C.B...",
    "CAAB..",
    "ABB...",
]

[[pattern]]
field = [
    "B.....",
    "AACDED",
    "ABBCDD",
    "BCCEEE",
]

# ----------------------------------------------------------------------
# ZABUTON

[[pattern]]
field = [
    "BA....",
    "AA....",
    "BC....",
    "BBD.D.",
    "CCCDD."
]

[[pattern]]
field = [
    "BA....",
    "AA....",
    "BC..E.",
    "BBDEDE",
    "CCCDDE"
]

[[pattern]]
field = [
    "B.....",
    "AA....",
    "BCA.E.",
    "BBDEDE",
    "CCCDDE"
]

[[pattern]]
field = [
    "AB..D.",
    "AACDCD",
    "BBBCCD"
]

# ----------------------------------------------------------------------
# DOUSHOKU

[[pattern]]
field = [
    "...BBA",
    "BBBCAA",
    "...BBB"
]

[[pattern]]
field = [
    ".D.BBA",
    "BBBCAA",
    "DDDBBB"
]

[[pattern]]
field = [
    ".....A",
    "...EEE",
    ".D.BBA",
    "BBBCAA",
    "DDDBBB"
]

# ----------------------------------------------------------------------
# NAMEKUJI

[[pattern]]
field = [
    "B.....",
    "A.....",
    "C.....",
    "C.....",
    "DD....",
    "CD....",
    "CB....",
    "ABB...",
    "AA....",
]
