# ----------------------------------------------------------------------
# GTR-HEAD

[[pattern]]
field = [
    ".A....",
    "BA....",
    "AA....",
    "BC....",
    "BBC...",
    "CC....",
]
ignition = 2

[[pattern]]
field = [
    "......",
    "BA....",
    "AAA...",
    "BC....",
    "BBC...",
    "CC....",
]
ignition = 2

[[pattern]]
field = [
    "A.....",
    "ABC...",
    "AABCC.",
    "BBC...",
]
ignition = 1

[[pattern]]
field = [
    "A.....",
    "ABC...",
    "AABCCC",
    "BBC...",
]
ignition = 1

[[pattern]]
field = [
    "A.C...",
    "ABC...",
    "AABC..",
    "BBC...",
]
ignition = 1

[[pattern]]
field = [
    "..B...",
    "..BC..",
    ".AABCC",
    "AABC..",
]
ignition = 2

[[pattern]]
field = [
    "..BC..",
    "..BC..",
    ".AABC.",
    "AABC..",
]
ignition = 2

[[pattern]]
field = [
    ".....C",
    "..AB.C",
    "..AABB",
    "..ABCC",
]
ignition = 3

# ----------------------------------------------------------------------
# GTR-TAIL

[[pattern]]
field = [
    "....CC",
    "...CBC",
    "..AAAA",
    "..ABBB",
]
ignition = 3

[[pattern]]
field = [
    "....C.",
    "...CBC",
    "..AAAC",
    "..ABBB",
]
ignition = 3

# ----------------------------------------------------------------------
# NEWGTR-HEAD

[[pattern]]
field = [
    "A.BC..",
    "AAABCC",
    "BBBC..",
]
ignition = 1
