[[pattern]]
field = [
    "ABC...",
    "AABCC.",
    "BBC...",
]

[[pattern]]
field = [
    "B.....",
    "AAA...",
    "BC....",
    "BBC...",
    "CC....",
]

[[pattern]]
field = [
    "BA....",
    "AA....",
    "BC....",
    "BBC...",
    "CC....",
]

[[pattern]]
field = [
    "AB....",
    "AAC...",
    "BBBC..",
    "CCC..."
]

[[pattern]]
field = [
    "C.....",
    "CBB...",
    "BAA...",
    "BCCA..",
]
