[[pattern]]
field = [
    "3.....",
    "322...",
    "211*..",
    "2331..",
]

[[pattern]]
field = [
    "2*....",
    "111...",
    "23....",
    "223...",
    "33....",
]

[[pattern]]
field = [
    ".*....",
    "21....",
    "11....",
    "23....",
    "223...",
    "33....",
]
