# ----------------------------------------------------------------------
# GTR-CORE

[[pattern]]
field = [
    "A.....",
    "ABC...",
    "AABCC.",
    "BBC@@.",
]
ignition = 1

[[pattern]]
field = [
    "A.....",
    "ABC...",
    "AABCCC",
    "BBC@@@",
]
ignition = 1

[[pattern]]
field = [
    "A.C...",
    "ABC...",
    "AABC..",
    "BBC@..",
]
ignition = 1

[[pattern]]
field = [
    "A.....",
    "ABC...",
    "AABC..",
    "BB.CC.",
]
ignition = 1

[[pattern]]
field = [
    "A.....",
    "ABC...",
    "AABCC.",
    "BB..C.",
]
ignition = 1

# ----------------------------------------------------------------------
# GTR-HEAD-1

[[pattern]]
field = [
    ".A....",
    "BA....",
    "AA....",
    "BC....",
    "BBC...",
    "CC....",
]
ignition = 2

[[pattern]]
field = [
    "BA....",
    "AAA...",
    "BC@...",
    "BBC...",
    "CC@...",
]
ignition = 2

[[pattern]]
field = [
    "B.....",
    "AA....",
    "AA....",
    "BC....",
    "BBC...",
    "CC@...",
]
ignition = 2

[[pattern]]
field = [
    "BA....",
    "AA....",
    "A@....",
    "BC....",
    "BBC...",
    "CC@...",
]
ignition = 2

[[pattern]]
field = [
    "B.....",
    "BA....",
    "AA....",
    "AC....",
    "BBC...",
    "CC@...",
]
ignition = 2

# ----------------------------------------------------------------------
# GTR-HEAD-2

[[pattern]]
field = [
    "A.....",
    "AB....",
    "AA....",
    "CB....",
    "BB....",
    "C.....",
    "CC....",
    "......",
]
ignition = 1

[[pattern]]
field = [
    "C.....",
    "B.....",
    "B.....",
    "BA....",
    "AA....",
    "AB....",
    "C.....",
    "CC....",
    "......",
]
ignition = 2

[[pattern]]
field = [
    "C.....",
    "B.....",
    "B.....",
    "AA....",
    "AB....",
    "AB....",
    "C.....",
    "CC....",
    "......",
]
ignition = 2

[[pattern]]
field = [
    "C.....",
    "B.....",
    "B.....",
    "AA....",
    "BA....",
    "BA....",
    "C.....",
    "CC....",
    "......",
]
ignition = 2

# ----------------------------------------------------------------------
# GTR-HEAD-3

[[pattern]]
field = [
    "C.....",
    "CB....",
    "BAA...",
    "BCA...",
    "BCA...",
    ".@@...",
    "......",
    "......",
]
ignition = 3

# ----------------------------------------------------------------------
# GTR-TAIL-1

[[pattern]]
field = [
    "....C.",
    "..B.C.",
    ".AABBC",
    "AAB@@C",
]
ignition = 2

[[pattern]]
field = [
    "..B...",
    "..BC..",
    ".AABCC",
    "AABC@@",
]
ignition = 2

[[pattern]]
field = [
    "..BC..",
    "..BC..",
    ".AABC.",
    "AABC@.",
]
ignition = 2

# ----------------------------------------------------------------------
# GTR-TAIL-2

[[pattern]]
field = [
    "....C.",
    "...CBC",
    "..AAAC",
    "..ABBB",
]
ignition = 3

[[pattern]]
field = [
    ".....C",
    "...BBC",
    "..AAAB",
    "..ACCB",
]
ignition = 3

[[pattern]]
field = [
    "....CC",
    "...CBC",
    "..AAAA",
    "..ABBB",
]
ignition = 3

[[pattern]]
field = [
    ".....C",
    "..AB.C",
    "..AABB",
    "..ABCC",
]
ignition = 3

[[pattern]]
field = [
    "..ABCB",
    "..AABB",
    "..ACCC",
]
ignition = 3

[[pattern]]
field = [
    ".....C",
    "...BCC",
    "..AABB",
    "..AABC",
]
ignition = 3

# ----------------------------------------------------------------------
# GTR-TAIL-3

[[pattern]]
field = [
    ".....C",
    ".....C",
    ".....B",
    "...CCB",
    "...BBA",
    "...AAA",
]

[[pattern]]
field = [
    ".....C",
    "....BC",
    "...ABC",
    "...AAB",
    "...ABC",
]
ignition = 4

[[pattern]]
field = [
    ".....C",
    "....BC",
    "...ABB",
    "...AAC",
    "...ABC",
]
ignition = 4

# ----------------------------------------------------------------------
# GTR-AIR

[[pattern]]
field = [
    "A.....",
    "ABC...",
    "AABCC.",
    "BBC...",
    "......",
    "......",
    "......",
]
ignition = 1

# ----------------------------------------------------------------------
# NEWGTR-CORE

[[pattern]]
field = [
    "A.BC..",
    "AAABCC",
    "BBBC@@",
]
ignition = 1

[[pattern]]
field = [
    ".ABC..",
    "AAABCC",
    "BBBC@@",
]
ignition = 2

[[pattern]]
field = [
    "A.BC..",
    "AAABC.",
    "BBBCC.",
]
ignition = 1

[[pattern]]
field = [
    ".ABC..",
    "AAABC.",
    "BBBCC.",
]
ignition = 2

# ----------------------------------------------------------------------
# NEWGTR-HEAD-1

[[pattern]]
field = [
    ".A....",
    "BA....",
    "AAC...",
    "BBBC..",
    "CCC@..",
]
ignition = 2

[[pattern]]
field = [
    "A.....",
    "AB....",
    "AAC...",
    "BBBC..",
    "CCC@..",
]
ignition = 1

# ----------------------------------------------------------------------
# NEWGTR-TAIL-1

[[pattern]]
field = [
    "....C.",
    "...BC.",
    "..AABC",
    "AAABBC",
]
ignition = 2

[[pattern]]
field = [
    ".....C",
    "...B.C",
    "..AABB",
    "AAABCC",
]
ignition = 2

[[pattern]]
field = [
    ".....C",
    ".....C",
    "....BC",
    "....BB",
    "...AAA",
    "...ABC",
]
ignition = 4

[[pattern]]
field = [
    ".....C",
    ".....C",
    "....CB",
    "....CB",
    "...AAA",
    "...ABB",
]
ignition = 4

# ----------------------------------------------------------------------
# FUKIGENGTR-CORE

[[pattern]]
field = [
    "BA....",
    "AAC...",
    "ABBC..",
    "BCC@..",
]
ignition = 2

# ----------------------------------------------------------------------
# FUKIGENGTR-HEAD-1

[[pattern]]
field = [
    "C.....",
    "B.....",
    "AA....",
    "BA....",
    "BA....",
    "BCC...",
    "C@@...",
]
ignition = 2

# ----------------------------------------------------------------------
# FUKIGENGTR-HEAD-2

[[pattern]]
field = [
    "CB....",
    "BAA...",
    "CBA...",
    "CBA...",
    "C.....",
    "......",
]
ignition = 3

# ----------------------------------------------------------------------
# ZABUTONL-CORE

[[pattern]]
field = [
    "A.....",
    "AB....",
    "AAC.C.",
    "BBBCC."
]
ignition = 1

# ----------------------------------------------------------------------
# ZABUTONL-HEAD-1

[[pattern]]
field = [
    "BA....",
    "AAA...",
    "BC@...",
    "BB@...",
    "CCC..."
]
ignition = 2

# ----------------------------------------------------------------------
# ZABUTONL-TAIL-1

[[pattern]]
field = [
    "....C.",
    ".ABCBC",
    "AAABBC"
]
ignition = 2

# ----------------------------------------------------------------------
# ZABUTONL-TAIL-2

[[pattern]]
field = [
    "....C.",
    "...CBC",
    "..CBAB",
    "..AAAB"
]

# ----------------------------------------------------------------------
# DAA

[[pattern]]
field = [
    "ABC...",
    "AABCC.",
    "ABBC@."
]
ignition = 1

[[pattern]]
field = [
    "..B.C.",
    ".AABBC",
    ".AABCC"
]
ignition = 2

[[pattern]]
field = [
    "..BC..",
    ".AABBC",
    ".AABCC"
]
ignition = 2

[[pattern]]
field = [
    "..BC..",
    ".AABCC",
    ".AABBC"
]
ignition = 2

# ----------------------------------------------------------------------
# YAYOI

[[pattern]]
field = [
    "BAA...",
    "AAC...",
    "BBBCCC",
    "@@@@@@"
]
ignition = 3

[[pattern]]
field = [
    "......",
    "A.B.C.",
    "AAABBB",
    "@@@CCC"
]
ignition = 1

[[pattern]]
field = [
    "......",
    "A.B..C",
    "AAABBB",
    "@@@CCC"
]
ignition = 1

[[pattern]]
field = [
    "......",
    ".AB.C.",
    "AAABBB",
    "@@@CCC"
]
ignition = 2

[[pattern]]
field = [
    "......",
    ".AB..C",
    "AAABBB",
    "@@@CCC"
]
ignition = 2

[[pattern]]
field = [
    "......",
    "...C.B",
    "..AAAA",
    "CCCBBB"
]
ignition = 3

[[pattern]]
field = [
    "......",
    "...CB.",
    "..AAAA",
    "CCCBBB"
]
ignition = 3

# ----------------------------------------------------------------------
# NAMEKUJI



# ----------------------------------------------------------------------
# LLR

[[pattern]]
field = [
    "A.....",
    "ABC...",
    "AABC..",
    "CCBB.."
]
ignition = 1

[[pattern]]
field = [
    "A.....",
    "ABC...",
    "AABB..",
    "CCBC.."
]
ignition = 1

[[book]]
field = [
    "A.....",
    "ACBB..",
    "AACD.D",
    "BBCCDD"
]
ignition = 1
