# ----------------------------------------------------------------------
# GTR

[[pattern]]
field = [
    "ABC...",
    "AABCC.",
    "BBC...",
]

[[pattern]]
field = [
    "..C...",
    "ABC...",
    "AABC..",
    "BBC...",
]

[[pattern]]
field = [
    "......",
    "ABC...",
    "AABC..",
    "BBCC..",
]

[[pattern]]
field = [
    "B.....",
    "AAA...",
    "BCD...",
    "BBCD..",
    "CCDD..",
]

[[pattern]]
field = [
    "..C...",
    "ABCDED",
    "AABCDD",
    "BBCEEE",
]

[[pattern]]
field = [
    "..B...",
    "..BCDC",
    "..ABCC",
    "AABDDD",
]

[[pattern]]
field = [
    "ABC...",
    "AABCD.",
    "BBDCC.",
]

[[pattern]]
field = [
    "B.....",
    "AAA...",
    "BC....",
    "BBC...",
    "CC....",
]

[[pattern]]
field = [
    "BA....",
    "AA....",
    "BC....",
    "BBC...",
    "CC....",
]

[[pattern]]
field = [
    "B.....",
    "A.....",
    "AA....",
    "BCD...",
    "BBCDD.",
    "CCD...",
]

[[pattern]]
field = [
    "B.....",
    "A.....",
    "AAD...",
    "BCDD..",
    "BBC...",
    "CCD...",
]

[[pattern]]
field = [
    "B.....",
    "A.....",
    "AA....",
    "BCD...",
    "BBCDDD",
    "CC....",
]

[[pattern]]
field = [
    "B.....",
    "B.....",
    "AA....",
    "AC....",
    "BBC...",
    "CC....",
]

# ----------------------------------------------------------------------
# GTR-TAIL

[[pattern]]
field = [
    "C.....",
    "CBB...",
    "BAA...",
    "BCCA..",
]

field = [
    "......",
    "..BCC.",
    "..ABBC",
    "AAB..C",
]

# ----------------------------------------------------------------------
# NEWGTR

[[pattern]]
field = [
    "..B...",
    "AAAB..",
    "BBB..."
]

[[pattern]]
field = [
    "..BC..",
    "AAABCC",
    "BBBC..",
]

[[pattern]]
field = [
    ".....D",
    "..BCDD",
    "AAABCC",
    "BBBCD.",
]

[[pattern]]
field = [
    "AB....",
    "AAC...",
    "BBBC..",
    "CCC..."
]

[[pattern]]
field = [
    "B.....",
    "A.....",
    "ABCD..",
    "ABBCDD",
    "CCCD.."
]

[[pattern]]
field = [
    "C.....",
    "B.....",
    "AA....",
    "BA....",
    "BBD...",
    "CCCD..",
    "DDD...",
]

[[pattern]]
field = [
    "C.....",
    "B.....",
    "B.....",
    "A.....",
    "AB....",
    "ABD...",
    "CCCD..",
    "DDD..."
]

# ----------------------------------------------------------------------
# FUKIGEN-GTR

[[pattern]]
field = [
    "A.....",
    "C.....",
    "C.....",
    "D.....",
    "D.....",
    "C.B...",
    "CAAB..",
    "ABB...",
]

# ----------------------------------------------------------------------
# ZABUTON

[[pattern]]
field = [
    "BA....",
    "AA....",
    "BC....",
    "BBD.D.",
    "CCCDD."
]

[[pattern]]
field = [
    "BA....",
    "AA....",
    "BC..E.",
    "BBDEDE",
    "CCCDDE"
]

[[pattern]]
field = [
    "B.....",
    "AAA...",
    "BC*.E.",
    "BBDEDE",
    "CCCDDE"
]

[[pattern]]
field = [
    "AB..D.",
    "AACDCD",
    "BBBCCD"
]

# ----------------------------------------------------------------------
# DOUSHOKU

[[pattern]]
field = [
    "...BBA",
    "BBBCAA",
    "...BBB"
]

[[pattern]]
field = [
    ".D.BBA",
    "BBBCAA",
    "DDDBBB"
]

[[pattern]]
field = [
    ".....A",
    "...EEE",
    ".D.BBA",
    "BBBCAA",
    "DDDBBB"
]
