[[pattern]]
field = [
    "ABC...",
    "AABCC.",
    "BBC...",
]

[[pattern]]
field = [
    "B.....",
    "AAA...",
    "BC....",
    "BBC...",
    "CC....",
]

[[pattern]]
field = [
    "BA....",
    "AA....",
    "BC....",
    "BBC...",
    "CC....",
]

# ----------------------------------------------------------------------

[[pattern]]
field = [
    "..B...",
    "AAAB..",
    "BBB..."
]

[[pattern]]
field = [
    "AB....",
    "AAC...",
    "BBBC..",
    "CCC..."
]

[[pattern]]
field = [
    "C.....",
    "B.....",
    "B.....",
    "A.....",
    "AB....",
    "ABD...",
    "CCCD..",
    "DDD..."
]

# ----------------------------------------------------------------------

[[pattern]]
field = [
    "C.....",
    "CBB...",
    "BAA...",
    "BCCA..",
]
